### ISSUE TITLE
Save setting without localStorage

### ISSUE THREAD

**Issue by WesselKroos** [WesselKroos/youtube-ambilight#1]
**Detailed error message:**
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

- [x] Use extension local storage (**storage.local**) https://developer.chrome.com/apps/storage
- [x] Migrate existing settings from **localStorage** to the **storage.local**

**Comment by Deagan** [comment]
I agree, I think a Cookie would be good, I can autoclean those easily, and prevent Ambilight from deleting itself!

Do addons/extensions have their own storage that settings can be stored in? I'm not familiar with the mechanisms, but I assume other extensions store their settings seperate from the websites they affect?

**Comment by WesselKroos** [comment]
> Do addons/extensions have their own storage that settings can be stored in? I'm not familiar with the mechanisms, but I assume other extensions store their settings seperate from the websites they affect?

Yes they do, those are no cookies, but those settings can only be saved an x amount of times per minute. So I'll have to throttle that a bit and then I can migrate the settings to the "extension storage".
