### ISSUE TITLE
Disable setting hotkey

### ISSUE THREAD

**Issue by Deagan** [WesselKroos/youtube-ambilight#109]
**Is your feature request related to a problem? Please describe.**
I often press the various Ambilight hotkeys accidentally, causing my video to change unexpectedly.

**Describe the solution you'd like**
I'd like to be able to enable/disable hotkeys, and/or assign them to different keys (including "none").

**Describe alternatives you've considered**
- A userscript that would disable the hotkey functionality completely, causing the button to be disabled on the webpage.
- I suppose the user could manually remove these hotkeys from the code, then recompile, but having it within the extension itself would be greatly appreciated!

**Comment by WesselKroos** [comment]
@Deagan It's already possible to assign the hotkeys to other keys. (For example, to change the hotkey for black bar detection, click on the hotkey input field in the brackets **[B]** and press another key.)

But it's not yet possible to set it to none. Great suggestion, I'll make it possible to remove the hotkey in the next version.

**Comment by Deagan** [comment]
Ah, I see, I didn't know I could just click to change! For now, I have changed all hotkeys to "^", but will await the next release to set to "None" officially. Thank you!
