### ISSUE TITLE
Random Jitter Effect when I use Edge Size

### ISSUE THREAD

**Issue by LesterLikee** [WesselKroos/youtube-ambilight#149]
## Describe the bug
Random Jitter Effect when I use Edge Size

## To reproduce
It's Random

## Screenshots
I recorded a video LINK :- https://drive.google.com/file/d/1a4IhbBfBpGH2LeyKvCgfiZc-poXXu24J/view?usp=sharing

See Last 10 seconds 

## Desktop (please complete the following information):
 - OS: Windows 11
 - Browser: Chrome
 - Browser version: 108.0.5359.125 (Official Build) (64-bit)
 - Extension version: 2.36.33

## Other extensions:
Nope

## Additional context
I made a video regarding it Link :- https://drive.google.com/file/d/1a4IhbBfBpGH2LeyKvCgfiZc-poXXu24J/view?usp=sharing

**Comment by WesselKroos** [comment]
That's a strange bug. It could be related to issue #97 

@LesterLikee What CPU and GPU are you using? And what are your settings?

**Comment by LesterLikee** [comment]
i9
3070

All settings are default

And is it also happening just as frequently when you turn on the experimental "WebGL renderer"?
Yes

**Comment by WesselKroos** [comment]
Can you try the workaround that I described in this comment?
https://github.com/WesselKroos/youtube-ambilight/issues/97#issuecomment-950353140

**Comment by LesterLikee** [comment]
sorry for the late reply 
I tried it doesn't work

**Comment by WesselKroos** [comment]
Hmm... 
It could still be another hardware acceleration bug in Chrome. Does it still happen when you disable hardware acceleration in the Chrome settings?

![image](https://user-images.githubusercontent.com/31220528/212436614-2c4ee765-80a1-41ec-acfa-9a27d72134af.png)

**Comment by WesselKroos** [comment]
Todo:
- [ ] Check if this bug still happens after the workaround for bug #150 is released

**Comment by LesterLikee** [comment]
yes
still happnes

**Comment by WesselKroos** [comment]
> yes still happnes

I know, it's just a todo checklist for myself 😉 after I've released the new version

**Comment by WesselKroos** [comment]
@LesterLikee A new update has been released to the extension on the Edge browser which might fix the jitter effect. Could you check if you have the same jitter issue in Edge as in Chrome? You can find the extension for Edge via this link: https://microsoftedge.microsoft.com/addons/detail/ambient-light-for-youtube/cmggdjjjfembmemhleknmfpakmgggjcf

**Comment by WesselKroos** [comment]
@LesterLikee I also found a way for me to reproduce the same kind of flickering that you are experiencing, but way more often.
This happens when I set the ANGLE flag in Chrome to OpenGL. This could be a new bug in chromium (Edge and Chrome).
![image](https://user-images.githubusercontent.com/31220528/217059589-ec98e273-c4d0-4f52-b40f-2f1fcf5c8695.png)

It could be that Edge's ANGLE flag is set to "Default" and that Edge is using OpenGL by default for your device. In that case you can try to force the flag to another value. I would suggest that you go to these settings edge://flags/#use-angle and first try out D3D11, then D3D9, D3D11on12 or OpenGL.

**Comment by WesselKroos** [comment]
@LesterLikee The new version is now available in the Chrome store. Please let me know if it has resolved your issue.

**Comment by WesselKroos** [comment]
@LesterLikee Can you let me know if it has been solved?

**Comment by WesselKroos** [comment]
I'll close this issue. Feel free to re-open if still relevant.
