### ISSUE TITLE
Ambient light not loaded because the video cannot be found on the watch page

### ISSUE THREAD

**Issue by Nate-Zephyr** [WesselKroos/youtube-ambilight#154]
Hello!
YouTube have added their own ambient to some videos.
Now your extension is overridden by that and doesn't work at all, even the settings button disappears.
Please do something with that because your version of ambient is much better.

**Comment by WesselKroos** [comment]
You might have the same issue as #154
Make sure that you are on version 2.37.7 or higher.

**Comment by Nate-Zephyr** [comment]
![image](https://user-images.githubusercontent.com/68021365/217070325-478b7f19-493c-4fb3-93e9-9782bff184fe.png)

**Comment by Nate-Zephyr** [comment]
The thread you sent me didn't give me anything.
I attached a screenshot from the console window, this is the only error related to this extension or WebGL.

Also, I checked even small channels and unpopular videos, it looks like YouTube finally introduced its own ambient feature for everyone.

**Comment by WesselKroos** [comment]
On what version of the extension and on what browser are you?

**Comment by WesselKroos** [comment]
In case that can only mean that the ambient light extension cannot find the `<video>` element in the webpage. But then it should, or not exist, or be at a location that is unknown to me.

Can you make a screenshot of the html structure with the location of the `<video>` in it?

For example:
![image](https://user-images.githubusercontent.com/31220528/217074897-19c111d6-492d-40b4-8993-d93479b8c311.png)

**Comment by WesselKroos** [comment]
Or it's maybe because of this setting. Can you turn of "Inline playback" in the YouTube settings and check if that fixes it if you refresh the page?

![image](https://user-images.githubusercontent.com/31220528/217075832-9aad830a-9f79-473f-9475-f61f82966588.png)

**Comment by WesselKroos** [comment]
> Also, I checked even small channels and unpopular videos, it looks like YouTube finally introduced its own ambient feature for everyone.

Btw, that's true. But my extension overrides YouTube's ambient feature even when it is enabled.

**Comment by WesselKroos** [comment]
Another thing that we can check is if you can find the video element on the video webpage yourself by executing the javascript query selector:
`document.querySelector('ytd-app ytd-watch-flexy video.html5-main-video')`

It should return the video element like this:
![image](https://user-images.githubusercontent.com/31220528/217077261-29b757c4-4342-4ddc-a110-096800bdbc2d.png)

**Comment by Nate-Zephyr** [comment]
![image](https://user-images.githubusercontent.com/68021365/217347837-4fd018a1-b1ca-4907-a5b5-db254bf0ecc9.png)
![image](https://user-images.githubusercontent.com/68021365/217347982-f680cf28-a0c9-4ac7-8cc8-f0d9c4921912.png)

Sorry but everything is same

**Comment by WesselKroos** [comment]
1. Can you answer this question from me as well?
> Another thing that we can check is if you can find the video element on the video webpage yourself by executing the javascript query selector: `document.querySelector('ytd-app ytd-watch-flexy video.html5-main-video')`
> 
> It should return the video element like this: ![image](https://user-images.githubusercontent.com/31220528/217077261-29b757c4-4342-4ddc-a110-096800bdbc2d.png)

2. I can only see the video element in your html screenshot. Can you re-take the screenshot of the html with all these 3 elements in it: `<body>`, `<ytd-watch-flexy>` and `<video>`?

3. I notice that there is a `zoom-to-fill` class on the `<video>`. That is a difference that I notice between your and mine html. It could indicate that YouTube is A/B testing a new feature that I do not have yet. Can you explain to me what this "zoom to fill" feature does?
![image](https://user-images.githubusercontent.com/31220528/217382831-1774f4da-07c8-482b-8dd5-e5b6a8501d72.png)

**Comment by Nate-Zephyr** [comment]
1.
![image](https://user-images.githubusercontent.com/68021365/217481700-3e90b72e-c875-4f1d-9348-62542fa55844.png)

2. 
![image](https://user-images.githubusercontent.com/68021365/217479029-99901993-71ab-466f-bc67-75068a43533d.png)
![image](https://user-images.githubusercontent.com/68021365/217479548-2466938c-bb87-4482-83e8-54c4b9453519.png)
![image](https://user-images.githubusercontent.com/68021365/217480101-e0a0e67c-c3de-4045-af4a-4b1c06de38a7.png)

3. This is another extension that I use for freely scaling videos because my monitor is 32:9 xD

4. Funny, your extension works in incognito mode, both if I enable only yours, and if I enable all my extensions in incognito mode...

**Comment by WesselKroos** [comment]
> 4. Funny, your extension works in incognito mode, both if I enable only yours, and if I enable all my extensions in incognito mode...

Aha, Then it's probably caused by a setting/feature of another extension. 
Let me know when you have figured out which extension setting/feature is causing it. Then I can reproduce it in my browser and see if I can fix it for you.

**Comment by Nate-Zephyr** [comment]
DUDE!
You won't believe me, but I found a solution (but I don't like it)

How it was:

In incognito mode, I decided to try to log into my YouTube account. After logging into my account, your extension stopped working. Then I logged out of my account, and the extension worked again.

Then I tried to log out of the account in "non-incognito" mode. The extension started to work. But when I logged back into my account, the extension stopped working again.

Everything is cool, but it is extremely inconvenient for me to watch YouTube without my account. Is there something wrong with my account settings?

**Comment by Nate-Zephyr** [comment]
About your question:

Your extension works in incognito mode (and not incognito), with ALL of my extensions, I've allowed them ALL to run in incognito mode.

However, if I'm logged in, the extension stops working.

**Comment by Nate-Zephyr** [comment]
Sadly, it's definitely something related to my account. I tried to log into my other YouTube account, it's clean, there is no channel created, and the extension started to work...

**Comment by WesselKroos** [comment]
Wow, that's strange. Then it could be a specific setting account setting or something YouTube is A/B testing on your account.

Hmm... looking at the extension code it could be that it cannot find the video if there are multiple `ytd-app` elements in the html. Then it could be possible that the video is in a second or third `ytd-app` element. But normally there is only one `ytd-app` element.

Since I do not have your account... You could try to debug it yourself:
Set a breakpoint in this line in the extension code _(the line numbers might be different from yours)_:
![image](https://user-images.githubusercontent.com/31220528/217575500-695217dd-d2ef-4549-9494-ef4fc7a73fef.png)

Then check if the `ytdAppElem` is linking to the correct element in the html:
![image](https://user-images.githubusercontent.com/31220528/217576900-8354a9ab-f73d-4cde-a7d2-2e9c63f27414.png)

Or you could execute `document.querySelectorAll('ytd-app')` to check if there are multiple `ytd-app` elements.

Alternatively we we could have call, via Discord or another chat app, in which you can share your screen so that we can debug it together .

**Comment by Nate-Zephyr** [comment]
1. `PREF` cookie is not a problem i think. The value is the same for both accounts. I've tried to swap cookies of my accounts, I've tried to paste your cookie in my account.. Everything same.
Here is my `PREF` cookie value:
`tz=Europe.Warsaw&f6=40000000&f5=30000&f7=150&f3=8&f4=4000000`

2. Debugging xD
I just don't understand what I'am doing.
![image](https://user-images.githubusercontent.com/68021365/217715690-ddc9a6ee-572b-4889-bbce-4aa2db4095b2.png)

3. Ofc we could have a call via Discord. Here is my username. **Натаниэль Хуй#7740**
Today I have a day off. But please first text, then call.

**Comment by WesselKroos** [comment]
After analyzing the crash reports, I come to the conclusion that there are at least 400 users that had this issue. Probably most of them didn't notice it when the extension suddenly disappeared. And some of them are users that tried the extension, saw that it does not work and then uninstalled it.
