### ISSUE TITLE
The topbar doesn't get the ambient effect

### ISSUE THREAD

**Issue by avi12** [WesselKroos/youtube-ambilight#155]
## Describe the bug
The topbar doesn't get the ambient effect

## To reproduce
1. Go to any video
2. Look at the top bar

## Expected behavior
The effect should be applied

## Screenshot
![image](https://user-images.githubusercontent.com/6422804/217521598-ba98563a-c263-42ba-90c9-347e5572cbae.png)

## Desktop (please complete the following information):
 - OS: Win10 22H2
 - Browser: Brave
 - Browser version: 1.48.158
 - Extension version: 2.37.7

## Other extensions:
Does the bug still persist when you disable all other extensions? If not, which other extension conflicts with the Ambient light for YouTube extension? **Haven't tested**

## Additional context
The screenshot describes how it looks in light mode
In dark mode it's the same, except the YouTube logo's text color is white

**Comment by WesselKroos** [comment]
YouTube has changed their header styling. But this will be fixed when version 2.37.13 has been published to the Google Chrome webstore: #141
> **2.37.13**
> Fixes
>
> Hide YouTube's new header background styling

**Comment by avi12** [comment]
I'll close the issue then
If the bug resurfaces, I will reopen it

**Comment by WesselKroos** [comment]
Version 2.37.13 with the fix is now available in all stores
