### ISSUE TITLE
Extend the hotkey tooltip with information on how to disable a hotkey

### ISSUE THREAD

**Issue by Chirronupu** [WesselKroos/youtube-ambilight#165]
**Is your feature request related to a problem? Please describe.**
Settings are accidentally toggled via keyboard commands.

**Describe the solution you'd like**
An option to disable keyboard commands.

**Describe alternatives you've considered**
Not using a keyboard, however it is difficult to operate a PC and a web browser without one.

**Additional context**
Thanks for the extension, it looks great and works great!

**Comment by WesselKroos** [comment]
@Chirronupu You can already disable the keyboard commands by clicking on a keyboard command and pressing the escape (or space or enter) key:
![image](https://user-images.githubusercontent.com/31220528/227326094-439a84f7-ae29-46d1-a64b-e4587c02d765.png)

But I think I can make it more clear by adding that information to the current tooltip.
