### ISSUE TITLE
Weird darker area in dark mode

### ISSUE THREAD

**Issue by avi12** [WesselKroos/youtube-ambilight#169]
### Bug description

There's a darker area that appears in dark mode

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/6422804/235314321-66b8f899-4176-4f65-84f6-bccd1156bf6e.png)

### Browser

Microsoft Edge

### Operating system

Windows

### Extension version

2.37.24

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

I selected Edge but I'm using the Chrome version

**Comment by WesselKroos** [comment]
Yeah, I noticed that YouTube changed a few UI elements yesterday. The content shadow behind the buttons below the video player have also disappeared.

It will be fixed once the next version has been released: #168
