### ISSUE TITLE
Unwanted button borders from 2.37.26

### ISSUE THREAD

**Issue by ice051128** [WesselKroos/youtube-ambilight#172]
### Bug description

The latest release has introduced a border bug that was not there previously. In older version, there are no borders around buttons on the watch page which is the expected and correct behavior. Now, it overrides any custom CSS which should not be the case.
### Steps to reproduce the behavior

1. Update the extension to 2.37.26
2. Watch any video
3. Observe the buttons

Refer to screenshots for the issue:

How it looks now:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/49018832/818348b1-9986-4736-a398-5480bcf40038)

How it used to look:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/49018832/d0467bd4-509a-4ff0-8ec1-8b77992d3a02)

### Browser

Microsoft Edge

### Operating system

Windows

### Extension version

2.37.26

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [ ] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

**Comment by WesselKroos** [comment]
Thanks for your report. I didn't know that YouTube still displays those button in the old style for some users.

The buttons look like this on my account, which is the new YouTube style:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/b165cca7-575e-45e7-ad0d-84ba5561bc83)

- [ ] I'll make sure to remove the borders from the buttons with the old style in the next version

Is the rest of the old layout still styled correctly? (The related tags, playlists, transcripts, etc)

**Comment by ice051128** [comment]
> Thanks for your report. I didn't know that YouTube still displays those button in the old style for some users.
> 
> The buttons look like this on my account, which is the new YouTube style (ignore my custom dislike/like ratio bar):
> 
> ![image](https://user-images.githubusercontent.com/31220528/237766163-b165cca7-575e-45e7-ad0d-84ba5561bc83.png) ![image](https://user-images.githubusercontent.com/31220528/237767172-82fbdbfa-5b20-47ef-bab5-ab2ce8bbbc89.png)
> 
> * [ ]  I'll make sure to remove the borders from the buttons with the old style in the next version
> 
> Is the rest of the old layout still styled correctly and working? (The related tags, playlists, transcripts, video description, comments, etc)

Thanks for the quick reply, the rest of the old layout still works correctly

**Comment by WesselKroos** [comment]
@ice051128 I can't reproduce your bug when I turn off all YouTube's experiment flags:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/50e08c0c-1a60-4306-90d0-917b8e583aea)

Could you share the YouTube's experiment flags that are enabled in your account?
To do so:
1. Press F12 to open a DevTools window
2. Open the Console tab (if not already opened)
3. Type or paste this text and press enter: `ytcfg.get('EXPERIMENT_FLAGS')`
4. Right click on the text output and click on `Copy object`
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/e914b27f-663e-4e53-9763-76855004b52b)

**Comment by WesselKroos** [comment]
I found 3 experiment flags that change the style of the buttons, but none of them resulted in squared buttons with borders:

```
ytcfg.set('EXPERIMENT_FLAGS', {
    ...ytcfg.get('EXPERIMENT_FLAGS'),
    web_button_rework: false,
    web_modern_buttons: false,
    web_segmented_like_dislike_button: false
})
```

Could you maybe also list the other extensions that you are using? Maybe you are using an extension / custom stylesheet that styles some of the buttons back to the old layout?

**Comment by ice051128** [comment]
> I found 3 experiment flags that change the style of the buttons, but none of them resulted in squared buttons with borders:
> 
> ```
> ytcfg.set('EXPERIMENT_FLAGS', {
>     ...ytcfg.get('EXPERIMENT_FLAGS'),
>     web_button_rework: false,
>     web_modern_buttons: false,
>     web_segmented_like_dislike_button: false
> })
> ```
> 
> Could you maybe also list the other extensions that you are using? Maybe you are using an extension / custom stylesheet that styles some of the buttons back to the old layout? In that case it might be difficult to remove the borders on the old buttons, because YouTube removed the attribute `modern-metapanel` that made it possible for me to distinct between the old an new buttons with the css selector `ytd-watch-metadata[modern-metapanel]`

I'm using a custom CSS with stylus that brings back the old layout and it has worked up to 2.37.25 perfectly, turning this extension off fixes the border issue immediately.

I put the code in console but nothing shows up
![image](https://github.com/WesselKroos/youtube-ambilight/assets/49018832/5f8e68e5-52ae-4b8c-8068-8222919c1448)

**Comment by WesselKroos** [comment]
Aha, that explains a lot. The problem is that if I revert the stylesheet back to version 2.37.24 it brings back this bug in YouTube's new style:
https://github.com/WesselKroos/youtube-ambilight/issues/169

PS: Even if I remove the borders from the buttons you'll still be left with the modern style semi-transparent background on those buttons.

**Comment by WesselKroos** [comment]
I had some time to think about the available options.

With the philosophy of overriding YouTube's style as minimal as possible, I'm going to reduce the custom stylesheet so that the additional button borders are removed. This will still give you the semi-transparent background colors on buttons by default, but you can remove those by changing the "Buttons & boxes background color" setting to 0%:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/472820a7-08fe-4e15-ab33-77c061e66017)

This way the default modern style will also stay intact for others:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/4e58c8d2-46cf-4add-afa5-4704e4b08520)
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/c913d950-9572-44c8-85e7-2f2383e73eff)

**Comment by WesselKroos** [comment]
@ice051128 Version 2.37.27 has just been released to the Edge Add-ons store.
