### ISSUE TITLE
Black bars in theater mode

### ISSUE THREAD

**Issue by harsharora08** [WesselKroos/youtube-ambilight#177]
### Bug description

In theater mode, there are black bars all around the video

### Steps to reproduce the behavior

- open youtube
- play any video
- choose Theater mode (T)
- black borders!

### Browser

Chrome

### Operating system

Windows

### Extension version

2.37.28

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

Till about yesterday, videos in theater mode didn't have black borders and videos looked so good in the theater mode but today there are black borders around the video. 
So far I have tried
- resetting the settings
- reinstalling the extension

Attaching an image as example

These are the settings
![image](https://github.com/WesselKroos/youtube-ambilight/assets/41362690/3d2fcd34-8f34-4c53-a4bd-393b3525e708)
And this is an example video in incognito
![image](https://github.com/WesselKroos/youtube-ambilight/assets/41362690/8ff5c3b0-194a-4a66-a4d9-44b18ed2c096)

Earlier there were no black borders on any side of the video.

**Comment by WesselKroos** [comment]
Thanks for the bugreport.
This seems to be caused by a change in the html layout of the theater view that YouTube has made an hour ago.

I'll update the extension to make it compatible with the new theater layout.

**Comment by WesselKroos** [comment]
Luckily it was an easy fix! 🚀 

The update will be available in Firefox in an hour and the other browsers often need a workday to review updates.
You can track the status of the update per browser in this issue: https://github.com/WesselKroos/youtube-ambilight/issues/179

**Comment by harsharora08** [comment]
That's great to hear. Thank you.
