### ISSUE TITLE
Title bar will not hide

### ISSUE THREAD

**Issue by Nobaz** [WesselKroos/youtube-ambilight#178]
### Bug description

The title bar and related videos list will not hide in theater mode even with the option enabled to hide everything while in theater mode.

### Steps to reproduce the behavior

1: Open Youtube.
2: Play any video.
3: Choose Theater mode.
4: Increase size of video to cover the screen and where the title bar and related videos would be.
4: Turn on option to hide everything.
5: Title bar and related videos not hidden.

### Browser

Opera

### Operating system

Windows

### Extension version

2.37.28

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

The bar and list persist on screen and cover the video. Everything was fine, like normal until today when I restarted my computer and noticed that the title bar was no longer being hidden. I have tried reverting and using older versions of Ambilight, however the issue remains the same even on old releases. It has been some time since I've looked at my ambilight settings, but I seem to recall that hiding the title bar in theater mode used to be an option, which I no longer see (I assume that has been rolled into the option to hide everything). 
![Screenshot 2023-06-28 164648](https://github.com/WesselKroos/youtube-ambilight/assets/53431661/d4fb001e-06f9-4b7e-9309-5cbec37539aa)

The following is unrelated to this particular issue, but the appearance of this additional issue coincided with the appearance of the above issue. I noticed that black bars appeared on either side of my video and when I decreased the size of the video there was a black box behind the video that covers the ambilight, as mentioned in another issue. Neither of these were issues 24 hours ago. Turning on the option to remove black bars does nothing.
![Screenshot 2023-06-28 165256](https://github.com/WesselKroos/youtube-ambilight/assets/53431661/f3761660-2dfa-481a-97d8-7bb92dea7673)

**Comment by WesselKroos** [comment]
Thanks for the bugreport.
This seems to be caused by a change in the html layout of the theater view that YouTube has made an hour ago.

I'll update the extension to make it compatible with the new theater layout.

**Comment by WesselKroos** [comment]
Luckily it was an easy fix! 🚀 

The update will be available in Firefox in an hour and the other browsers often need a workday to review updates.
You can track the status of the update per browser in this issue: https://github.com/WesselKroos/youtube-ambilight/issues/179

**Comment by Nobaz** [comment]
Thank you! Have a good day.
