### ISSUE TITLE
Remove bars settings reset 

### ISSUE THREAD

**Issue by Angrycuack** [WesselKroos/youtube-ambilight#182]
**Troubleshooter**
First try all the checks and steps in the troubleshooter: https://github.com/WesselKroos/youtube-ambilight/blob/master/TROUBLESHOOT.md
1. Dit it solve your performance problems? no
3. What steps made it worse/better:

**Describe the performance you are currently experiencing**
4. The program works nice but after a while ( I think after updates ) the settings "remove bars" it's reset it to "on" ( I want it in "off" )

**Device information**
5. Name of your CPU: i5 8600K
6. Name of your GPU: RTX 2080 8GB
7. Name of the browser: Microsoft Edge
8. Version of the browser: Lastest

**Screenshots**
9. Add a screenshot of the Task manager with the CPU and GPU usage charts
https://gyazo.com/b107a58337731aff7ed68d401ae41405
10. Turn on the Ambient light setting Quality > Show framerate and make a screenshot of your framerates

**Describe the performance you would be happy with**
11.

**Describe any workaround you've tried so far**
12.

**Additional context**
13.

**Comment by WesselKroos** [comment]
@Angrycuack The setting "Remove black bars" is set to "off" by default. This hasn't changed in any update.

I think you might have accidentally pressed the "B" key on your keyboard which toggles the "Remove black bars" setting between on/off.
There are more settings with hotkeys:
- "A" to enable/disable the ambient light
- "V" to toggle the "Remove black sidebars" setting
- "S" to toggle the "Fill video to screen" setting

To disable a hotkey click on the hotkey in the settings menu and press the escape key:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/842d5ff0-cac5-4103-a1b9-13cd27405217)

**Comment by Angrycuack** [comment]
Aaaah okey, I'm sorry, I didn't know it
😓
Thank you so much for the help 😁👍🏻
