### ISSUE TITLE
YouTube interface acting weird with AmbiLight on

### ISSUE THREAD

**Issue by harsharora08** [WesselKroos/youtube-ambilight#184]
### Bug description

Some elements on youtube appear weird (white text on white bg)

### Steps to reproduce the behavior

without ambilight on
![image](https://github.com/WesselKroos/youtube-ambilight/assets/41362690/c90deac1-9329-4971-9745-b03eb8bea4bb)

with ambilight on
![image](https://github.com/WesselKroos/youtube-ambilight/assets/41362690/f03fbb4e-b6a9-4f17-8bb2-fb200bf572f6)

after scrolling down
![image](https://github.com/WesselKroos/youtube-ambilight/assets/41362690/e64a4720-82ca-4ec0-a2c7-52ce3e930d5c)

### Browser

Chrome

### Operating system

Windows

### Extension version

2.37.29

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

**Comment by WesselKroos** [comment]
@harsharora08 This is probably happening to you because you have set the "Buttons & boxes background opacity" setting to 100%. This causes the background of those boxes to be fully white:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/aa4e632b-e264-4b00-8c94-72c5fe6dcb63)

**Comment by harsharora08** [comment]
alright got it. fixed.
this happened abruptly today so i thought it was something to do with youtube's rework from the server end.

thank you for the response.

**Comment by Snakzi** [comment]
same happened to me out of nowhere. it was the background opacity, eventhough i didnt change it.

**Comment by WesselKroos** [comment]
Hmm, if there are so many people with this issue then there might be a bug in my migration code between updates.
I'll take a look this weekend to see what could cause this.
