### ISSUE TITLE
WebGL crash if "no fingerprint" on (Brave Browser)

### ISSUE THREAD

**Issue by luchettodj94** [WesselKroos/youtube-ambilight#188]
### Bug description

As title say if you enable that option WebGL crash, to my knowledge it wasn't before (unsure)

### Steps to reproduce the behavior

1. Settings
2. Protections
3. Block fingerprint (rigid)

### Browser

Chrome

### Operating system

Windows

### Extension version

2.37.29

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

**Comment by WesselKroos** [comment]
Which of the 2 fingerprint blocking setting values have you set it to?
I don't believe this has ever worked with Brave's "Aggressively block fingerprinting" turned on because then the browser blocks features of WebGL that the extension needs.

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/3edabe4b-761b-42ae-906b-b6f6ec51fd72)

**Comment by luchettodj94** [comment]
Was set on aggressive (sorry, I had another language set so my translation was based on it).
It doens't have much sense to keep it to "normal" since basically all your spec are in plain sight in this way.
Any fix?

**Comment by WesselKroos** [comment]
> Any fix?

Brave's "Aggressively block fingerprinting" blocks features of WebGL that the extension needs:
https://github.com/brave/brave-browser/issues/9188

It might also be good to know that Brave is considering to remove aggressive fingerprinting mode:
https://github.com/brave/brave-browser/issues/31229

**Comment by luchettodj94** [comment]
Thank you for the reply, actually I've just found from your screen that you can change the behavior for a specific website while still maintaining the agressive rule active in general.
