### ISSUE TITLE
Theatre mode issue

### ISSUE THREAD

**Issue by cw0rth** [WesselKroos/youtube-ambilight#190]
### Bug description

Not sure if you're already aware or have already found the issue. But previously I've been able to be in theatre mode with the ambient light and everything else on the screen hidden, but now it's just not working, and I'm stuck with the drag up "stuff" at the bottom of my screen.

### Steps to reproduce the behavior

1. Have theatre mode selected.
2. Have the toggle to hide everything else on screen while in theatre enabled.

### Browser

Chrome

### Operating system

Apple macOS

### Extension version

2.37.29

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [ ] When I logged out of my YouTube account (ex. in incognito mode)
- [ ] In incognito mode

### Additional context and/or screenshots

<img width="1440" alt="image" src="https://github.com/WesselKroos/youtube-ambilight/assets/142841707/ffe980d3-d555-4835-846e-117e5aedfa71">
<img width="1440" alt="image" src="https://github.com/WesselKroos/youtube-ambilight/assets/142841707/11f5e241-64ba-4e92-bdc8-1a70b6b1bc57">
---
It's just all broken, and I'm not sure why. It wasn't like this before.

**Comment by WesselKroos** [comment]
This is the same issue as #187
