### ISSUE TITLE
Export settings

### ISSUE THREAD

**Issue by luchettodj94** [WesselKroos/youtube-ambilight#191]
Hello, it would be useful if we could export our settings to easy import it to another browser.
The extension have many options and this is amazing however is a pain each time to check and manually add them back.

**Comment by luchettodj94** [comment]
> @luchettodj94 What is the reason you are often switching between browsers? And how often are you switching between browsers? Maybe there are other better ways than an export/import functionality to make life easier for you

Actually I'm not really switching browser that often (rn I'm stable with Brave beta), however I have multiple pc so getting the config out of it it will make the life easier + having a custom config for a friend it it'll make him simplier aswell.

As for you're question only recently had install multiple time the browser since brave standard have some issue with gpu cache that will cause to not load correctly the pages (from what I've understand is a chromium issue), however in brave beta is solved, so my process was Chrome -> Brave -> Brave Beta -> Brave beta again (cause tried to import broken wallet config from the standard one), so far I'm more than soddisfied.

**Comment by WesselKroos** [comment]
Hmm, I was thinking of importing from/exporting to a json file.
But in your case it might be slightly more helpful to import from/export to a Google/Brave account.

So I'm thinking of making both options available.

**Comment by luchettodj94** [comment]
Well if you can make an integrated backup in the extension that surely will be helpul aswell.

**Comment by WesselKroos** [comment]
**Progress**
- [ ] Migrate 3 settings with workarounds to another name (Version 2.37.33)
- [ ] Implement import/export functionality

**Comment by Desoroxxx** [comment]
Oh, that's a great idea, I reset my setting from time to time before coming here for more info on something potentially breaking, since I use the advanced and experimental features, so I prefer checking it's not related to them.

Thus, when I reset my settings to check, and it is not related to them, well, I need to set them back one by one, which is fairly annoying but minor considering I don't do it that often.

So having a way to permanently save my settings and be able to reset them to check if an issue still occurs and then reimport them would be a very cool quality of life feature.

**Comment by WesselKroos** [comment]
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/5e9c09b4-619e-42de-b475-257f5f102b92)

**Comment by luchettodj94** [comment]
Honestly I don't know how "Dark Reader" extesion work, they are using actively some direct backup with google, if you change browser or pc it will automatically download the custom settings.

**Comment by WesselKroos** [comment]
> Honestly I don't know how "Dark Reader" extesion work, they are using actively some direct backup with google, if you change browser or pc it will automatically download the custom settings.

There is a way to listen for changes in the cloud data. That way I can set up a permanent synchronization of the settings in the cloud. But that's a next step for another day.

**Comment by WesselKroos** [comment]
I see that most browser vendors have updated the extension to version 2.38.0 except for Edge.

@luchettodj94 @Desoroxxx Could you let me know if it works correctly? This is a first version, so I don't expect everything to be perfect. But I have placed some checks which should prevent obviously incorrect settings values from being imported.

**Comment by Desoroxxx** [comment]
I am on Edge sadly so will need to wait a bit.
I love Edge wish they're review process where better

**Comment by WesselKroos** [comment]
> I am on Edge sadly so will need to wait a bit.
> I love Edge wish they're review process was better

The previous release review took 9 workdays. Let's hope that they're quicker this time.

3 months ago they only needed one workday. So I hope this delay has something to do with a holiday instead of it being permanently slow.

**Comment by WesselKroos** [comment]
> Yes it was updated correctly however the option for backup might be a bit difficult to notice if you don't know that you have to click on the extension icon (perhaps just leave a notice in the settings somewhere). - @luchettodj94

Great suggestion. Maybe it is possible to create a button next to the "reset settings" button that automatically opens the popup and scrolls it to the import/export section.

**Comment by WesselKroos** [comment]
@Desoroxxx The Edge update has finally been reviewed

**Comment by Desoroxxx** [comment]
Amazing, seems to work perfectly.
