### ISSUE TITLE
Dark theme: Buttons & boxes background are 100% white while the setting is set to 10% white

### ISSUE THREAD

**Issue by luchettodj94** [WesselKroos/youtube-ambilight#195]
### Bug description

Youtube dark mode will break description, likes bar, etc.

### Steps to reproduce the behavior

Official dark mode enabled
dark mode in the extension
(light mode is grayed also)

### Browser

Chrome

### Operating system

Windows

### Extension version

2.37.34

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

<img width="1112" alt="Immagine 2023-09-15 080546" src="https://github.com/WesselKroos/youtube-ambilight/assets/57552558/d8552509-7970-4957-957c-fa9b30334df5">
It may be useful if we could disable this option at all.
(Right now I'm using Dark Reader extension to fix this behaviour)

**Comment by Desoroxxx** [comment]
Cam here to report the same been happening for a few weeks now and wonder why it wasn't fixed, here is my screenshot of it:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/82710983/0f167466-828c-4690-890d-1958fe4b02d9)

**Comment by WesselKroos** [comment]
Another user reported the same problem yesterday in an old issue. Could you check if the solution I had provided there also solves this problem?

This was the issue: 
https://github.com/WesselKroos/youtube-ambilight/issues/184

**Comment by luchettodj94** [comment]
> Another user reported the same problem yesterday in an old issue. Could you check if the solution I had provided there also solves this problem?
> 
> This was the issue: #184

ok, and tried and it will kida solve the issue, at least set at 2%, seem after the last update some settings got resetted or modified (like the "remove the black bar" ), however what it would be useful if we can turn off that settings since I personally prefer the official theme instead of having everything black or white.
<img width="238" alt="Immagine 2023-09-15 180031" src="https://github.com/WesselKroos/youtube-ambilight/assets/57552558/055f4e8f-3854-482f-a2ef-aa191e112208">

**Comment by WesselKroos** [comment]
Hmm, if there are so many people with this issue then there might be a bug in my migration code between updates.
I'll take a look this weekend to see what could cause this.

PS: It's not possible to use the default YouTube style because that style has no  transparent backgrounds.

**Comment by WesselKroos** [comment]
@luchettodj94 @Desoroxxx @Snakzi @harsharora08 Since you all had this problem recently, do you still know at what percentage you had set the "Buttons & boxes background opacity" originally before it was changed to 100% by the update?

**Comment by luchettodj94** [comment]
> @luchettodj94 @Desoroxxx @Snakzi @harsharora08 Since you all had this problem recently, do you still know at what percentage you had set the "Buttons & boxes background opacity" originally before it was changed to 100% by the update?

Unfortunately not, it was not a settings I've touched, however the closest to the default one is 2% I guess

**Comment by WesselKroos** [comment]
> (if you need more details just tell me quickly cause I will not keep the browser open forever :P )

Feel free to close the browser. I'm not logging anything when that warning appears. But this info should be enough for me to reproduce it. Let's see if I succeed today

**Comment by Desoroxxx** [comment]
> @luchettodj94 @Desoroxxx @Snakzi @harsharora08 Since you all had this problem recently, do you still know at what percentage you had set the "Buttons & boxes background opacity" originally before it was changed to 100% by the update?

It wasn't changed to 100% right now it is sitting at 10% and it everything is white

**Comment by WesselKroos** [comment]
> It wasn't changed to 100% right now it is sitting at 10% and it everything is white

Aha, that explains a lot to me. I'm always running at -10%, that's why I did not notice this bug.
But, I see the bug now as well. So, for some reason 10% is completely white.

That makes things easier. Because a sudden change by an update is hard to reproduce. But this should be easily fixable.

**Comment by luchettodj94** [comment]
> > It wasn't changed to 100% right now it is sitting at 10% and it everything is white
> 
> Aha, that explains a lot to me. I'm always running at -10%, that's why I did not notice this bug. But, I see the bug now as well. So, for some reason 10% is completely white.
> 
> That makes things easier. Because a sudden change by an update is hard to reproduce. But this should be easily fixable.

The pattern changed from max 20% to 100 so in this case got reset at maximum, before the dafault was 10% as in the pic I've show previously

**Comment by WesselKroos** [comment]
> The pattern changed from max 20% to 100
@luchettodj94 What do you mean by "the pattern"?

> It wasn't changed to 100% right now it is sitting at 10% and it everything is white
> > That makes things easier. Because a sudden change by an update is hard to reproduce. But this should be easily fixable.

Hmm, sad news. The cause is apparently a bug in the latest Chrome/Edge/Opera browser updates to Chromium version 117.
Because the opacity of the white background is still correctly set to 10% (a.k.a. 0.1) in the css but the background is painted/rendered by the browser with a 100% opacity.

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/ceea8506-2f72-4c2a-bc81-7e4d5a18d958)

I'm going to search for a workaround to bypass this browser bug. But if I can't find one, we might have to wait for a new browser version in which they have fixed this.

**Comment by WesselKroos** [comment]
I've reported the bug to the Chromium browser developers:
https://bugs.chromium.org/p/chromium/issues/detail?id=1483736

**Comment by WesselKroos** [comment]
I found a workaround, which I'll will release in the next version

**Comment by WesselKroos** [comment]
I see that most browsers vendors have updated the extension to version 2.38.0 except for Edge.

@luchettodj94 @Desoroxxx @avi12 Could you let me know if this issue has been resolved for all of you?

**Comment by avi12** [comment]
I'm using the Chrome extension and yesterday I encountered this issue when disabled the ambient effect

**Comment by WesselKroos** [comment]
> I'm using the Chrome extension and yesterday I encountered this issue when disabled the ambient effect

Version 2.38.0 has just been release today.

**Comment by luchettodj94** [comment]
> I see that most browsers vendors have updated the extension to version 2.38.0 except for Edge.
> 
> @luchettodj94 @Desoroxxx @avi12 Could you let me know if this issue has been resolved for all of you in version 2.38.0?

Yes it was updated correctly however the option for backup might be a bit difficult to notice if you don't know that you have to click on the extension icon (perhaps just leave a notice in the settings somewhere).

**Comment by Desoroxxx** [comment]
Just to confirm that this has been fixed on my side
