### ISSUE TITLE
Video buffers on seeking when AmbiLight is on

### ISSUE THREAD

**Issue by harsharora08** [WesselKroos/youtube-ambilight#199]
### Bug description

Video buffers for a while when I press forward or backward button, or when I press J and L.

### Steps to reproduce the behavior

1. Open any video
2. Press forward
3. Video takes a little buffering (My internet is very stable)
4. Turn off ambilight
5. Press forward
6. Video forwards instantly
7. Turn on ambilight and press forward
8. Forwards instantly with ambilight on too

I mean yes this is my workaround for now but it happens on every video which makes it tiresome to repeat the process.
If you want I can attach a screen recording replicating the issue if this does not happen with you.

### Browser

Chrome

### Operating system

Windows

### Extension version

2.38.0

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

**Comment by WesselKroos** [comment]
I'm unable reproduce this.
Could you attach a screenrecording and tell me which CPU and GPU you have?

**Comment by harsharora08** [comment]
I am sorry but even I am not able to reproduce the issue. It was happening last night a lot.
It can be because background processes I guess.
Next time if it happens, I will first screen record then open an issue.

Thank you and apologies for the inconvenience.

**Comment by WesselKroos** [comment]
Haha, no worries
