### ISSUE TITLE
Buttons are displayed in the wrong theme when the ambient light theme is set to another value than YouTube's settings

### ISSUE THREAD

**Issue by avi12** [WesselKroos/youtube-ambilight#201]
### Bug description

Incomplete dark/light mode

### Steps to reproduce the behavior

1. Be logged in
2. Start from light/dark mode
3. Change to the opposite theme

### Browser

Microsoft Edge

### Operating system

Windows

### Extension version

2.38.0

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [ ] When I logged out of my YouTube account (ex. in incognito mode)
- [ ] In incognito mode

### Additional context and/or screenshots

![image](https://github.com/WesselKroos/youtube-ambilight/assets/6422804/6bafd7e4-2165-4427-85db-7c73aff69b68)
Interestingly, when I either log out or open InPrivate (with the ext being the only one enabled), the bug is resolved
Note that I'm on Edge but running the CWS extension

**Comment by WesselKroos** [comment]
It seems like they have introduced some theme changes with their new live counters

**Comment by avi12** [comment]
Huh, very interesting
Let me know if you have a hotfix and you want me to try out a version before you release it to the stores

**Comment by WesselKroos** [comment]
It should be solved in this beta version:
[youtube-ambilight-v2.38.0.1.zip](https://github.com/WesselKroos/youtube-ambilight/files/13230814/youtube-ambilight-v2.38.0.1.zip)

**Comment by avi12** [comment]
I tried to set
![image](https://github.com/WesselKroos/youtube-ambilight/assets/6422804/8391a6c3-2a79-41f3-8d34-38ca5d34cc35)
when I do, it briefly switches to light theme and then back to dark theme

**Comment by WesselKroos** [comment]
> I tried to set ... when I do, it briefly switches to light theme and then back to dark theme

So it works?

**Comment by avi12** [comment]
https://github.com/WesselKroos/youtube-ambilight/assets/6422804/27260a12-327a-4cd6-a376-874856186e73

**Comment by WesselKroos** [comment]
What theme have you set in the Ambient light settings?

PS: This is also just a bug without the ambient light caused by YouTube's style on these buttons. So I've reported this bug to YouTube as well:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/7c285e59-0bb2-4861-b6a5-f1bca4dd0da0)

**Comment by avi12** [comment]
Notice how in the main post I mentioned that in the production version I only reproduce the bug when I'm logged into YouTube but when I'm not then I do not reproduce it

**Comment by WesselKroos** [comment]
> > What theme have you set in the Ambient light settings?
> 
> Just the defaults; I sideloaded the extension, opened a video and the result is in the screen recording

Then it works correctly. The YouTube theme is restored to dark theme when the theme is set to the dark theme in the extension.

> Notice how in the main post I mentioned that in the production version I only reproduce the bug when I'm logged into YouTube but when I'm not then I do not reproduce it

I'm also logged in and have fixed the same color issues in that test version. Can you send me a screenshot of the wrong button colors with this test version?

**Comment by avi12** [comment]
After setting the theme to Default, it behaves as expected

> Can you send me a screenshot of the wrong button colors with this test version?

Everything seems to be in the right color, as far as I can tell
![image](https://github.com/WesselKroos/youtube-ambilight/assets/6422804/994cec82-10af-45a2-b851-7aff9d020639)
