### ISSUE TITLE
A video with rounded corners has no rounded corners in the shadow

### ISSUE THREAD

**Issue by Skyefruit** [WesselKroos/youtube-ambilight#203]
### Bug description

Old video frame is visible behind the new rounded corners youtube introduced when using the ambient light extension

### Steps to reproduce the behavior

1. Open any video with the extension enabled.
2. The corner issue should be clearly visible on a bright video.

### Browser

Firefox

### Operating system

Windows

### Extension version

2.38.0

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

Full Page (Ambient Light ON)

![Screenshot 2023-11-15 151003](https://github.com/WesselKroos/youtube-ambilight/assets/150918539/97eb1879-b456-4b40-babe-17e2f695a390)
The Corner (Ambient Light ON)
![Screenshot 2023-11-15 151326](https://github.com/WesselKroos/youtube-ambilight/assets/150918539/670c09f1-a182-44b4-8819-7555b864d230)
YouTube's Own Ambient Light Mode (Extension Disabled)
![Screenshot 2023-11-15 151456](https://github.com/WesselKroos/youtube-ambilight/assets/150918539/c800671e-7f7f-4fd1-b165-133873a1db24)

**Comment by WesselKroos** [comment]
Thanks for your bugreport. It will be fixed in the next update:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/0b5a7f80-bf4a-47a6-8fca-53e2f9bfaffc)

**Comment by Skyefruit** [comment]
Looks great! You even found the same video and the timestamp thank you for your effort!
