### ISSUE TITLE
Ambient light always displays red after Nvidia GPU driver update

### ISSUE THREAD

**Issue by travilist** [WesselKroos/youtube-ambilight#206]
### Bug description

Ambient light always displays red after Nvidia GPU driver update

### Steps to reproduce the behavior

1. Update GeForce game ready driver to 546.29
2. Open YouTube video

### Browser

Chrome

### Operating system

Windows

### Extension version

2.38.0

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

Chrome ANGLE graphics backend is set to "OpenGL" instead of "D3D11" to fix flickering issues in YouTube. Application previously worked with this setting.

![chrome_fCpt4xRBaG](https://github.com/WesselKroos/youtube-ambilight/assets/38170702/5b4601b1-fb79-49d6-a398-5d7defcc82a9)

**Comment by WesselKroos** [comment]
@travilist That's a strange bug. We might need to report this to Google and/or NVidia to get this resolved if it's really a specific driver and/or hardware issue.

We might be able to already narrow it down to a specific hardware/software setup to help them out:
1. What is your graphics card model?
2. Did you also check if it happens with Angle set to D3D11?
3. What Windows version and build number are you on?
4. What is the refresh rate of your monitor and do you have a single or multiple monitors?
5. Have you specifically enabled/disabled any NVidia/Windows features that we could narrow this down to? (NVidia Video RTX VSR, GSync, GSync-compatible, Windows Hardware-Accelerated GPU Scheduling, Resizable BAR, Multi-Plane Overlay (MPO), etc)

**Comment by WesselKroos** [comment]
@travilist  I'm unable to reproduce this bug on Windows 11 with an NVidia RTX 2070 Super with NVidia GForce game ready driver version 546.29. Please provide your answers to the above questions and an export of your settings.

**Comment by travilist** [comment]
Sorry for the late response. With the new NVidia graphics driver (546.29), it seems as if rasterization is turned off in Chrome when using the OpenGL ANGLE backend. Switching to D3D11 re-enables rasterization and Ambient Light works again. Here are the following if they could still help:

1. NVidia RTX 4070 ti
2. Yes, this seems to fix the issue. It is just strange that OpenGL previously worked before the driver update.
3. Windows 11 Build 22631.2792
4. My primary monitor refreshes at 165Hz, I do have multiple monitors
5. I have not touched any of these settings

**Comment by WesselKroos** [comment]
I'm afraid that I can't fix this issue for you, instead you might have to report this issue to the Chromium or NVidia developers.
But we could try to narrow down what exactly fails.

I have scraped a bunch of old ambient light tests which you can try out. The question is then, which of these webpages display a copy or blurred copy of the video when you play the video and which ones display a red blurry square?

1. https://cdpn.io/pen/debug/LYgNzJK (Extra instructions: Click to play the video)
2. https://cdpn.io/pen/debug/eYVJLzY (Extra instructions: Play the video until 3 seconds, then click on the "Draw x times" button, wait 1 second and click on the "Draw x times" button again. Do all 2 destination column display 3 images?)
3. https://cdpn.io/pen/debug/OJOgeOa/40f653ddf52b4b6ce1934e472112527e
4. https://cdpn.io/pen/debug/wvPMERM/676794c8fefaba9d752ff08a565f0b16
5. https://cdpn.io/pen/debug/oNojvWb/f6cb7b1445755aa4574faeab82d98d39
6. https://cdpn.io/pen/debug/yLPyPVa
7. https://cdpn.io/pen/debug/gOMLyRp
8. https://cdpn.io/pen/debug/oNbXYXX
