### ISSUE TITLE
Ambient light will not trigger when watching 3D videos in 2D

### ISSUE THREAD

**Issue by ice051128** [WesselKroos/youtube-ambilight#207]
### Bug description

The ambient light is not visible when watching 3D videos in 2D

### Steps to reproduce the behavior

1. Try to watch a video like https://www.youtube.com/watch?v=7t2FyErNKuY
2. Ambient light will not trigger properly

### Browser

Microsoft Edge

### Operating system

Windows

### Extension version

2.38.0

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

**Comment by WesselKroos** [comment]
I've disabled the ambient light in 3D/VR videos since 2019 because there was no way to capture the image from a 3D video. But it might be worth investigating it once again.

**Comment by WesselKroos** [comment]
So far, I've got it partially working. 
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/b6bf7ee4-0686-4245-9ee4-443dab6732b3)


But after navigating to another VR video (or sometimes just randomly after a while) the image data becomes corrupted:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/0ad9f065-e5da-48bc-8530-cfbdbd45cd18)

**Comment by WesselKroos** [comment]
Apparently the corrupted image data only happens with chromiums D3D11on12 flag turned on.
