### ISSUE TITLE
ability to change the default shortcuts for ambilight 

### ISSUE THREAD

**Issue by kaem-e** [WesselKroos/youtube-ambilight#209]
It would be nice to have an option to be able to change/remap/disable the shortcuts that ambilight ships with by default. 
I'm in particular annoyed by `a` and `s` not being remappable as those are also what I use with [video speed controller](https://chromewebstore.google.com/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk) to adjust the playback speed of the video.

the solution I'm using at the moment is to use `Disable website key bindings` in video speed controller's advanced settings, but this is less than ideal probably.

**Comment by WesselKroos** [comment]
Check my answer on how to disable or remap hotkeys: https://github.com/WesselKroos/youtube-ambilight/issues/165#issuecomment-1481770589
