### ISSUE TITLE
Debanding does not work

### ISSUE THREAD

**Issue by ice051128** [WesselKroos/youtube-ambilight#210]
### Bug description

Debanding makes no visible difference even when it's toggled on

### Steps to reproduce the behavior

1. Watch any video
2. Check the difference with it on or off

At 0%
![Screenshot_7](https://github.com/WesselKroos/youtube-ambilight/assets/49018832/6106d5c9-958f-4434-b369-e31761ee84d2)

At 100%
![Screenshot_9](https://github.com/WesselKroos/youtube-ambilight/assets/49018832/0f26f76d-d7c8-41b1-ba0d-2d2f1b05af88)

U can still see all the color banding on the left and bottom

### Browser

Microsoft Edge

### Operating system

Windows

### Extension version

2.38.1

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

**Comment by WesselKroos** [comment]
I think you are looking at the wrong setting. You've enabled debanding in the video instead of the debanding setting in the ambient light.
