### ISSUE TITLE
Removing bars and "Fill video to screen" does not work on 4:3 videos where YouTube zooms in the video

### ISSUE THREAD

**Issue by zachpoblete** [WesselKroos/youtube-ambilight#212]
### Bug description

When in theater mode and "Hide everything in theater mode" is on, toggling "Fill video to screen" seems to have no effect.

### Steps to reproduce the behavior

1. Enter theater mode.
2. Enable "Enabled."
3. Enable "Hide everything in theater mode."
4. Enable "Fill video to screen."
5. Find that nothing has changed.

Maybe "Fill video to screen" is supposed to work under other conditions, but as a first-time user, I would expect that the setting would definitely work when in theater mode and "Hide everything in theater mode" is on, but still, nothing changes when I toggle "Fill video to screen."

### Browser

Chrome, Microsoft Edge, Firefox

### Operating system

Windows

### Extension version

2.38.1

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

I would expect that the borders of the video would extend until they hit the borders of the visible page, but there remains space between all the borders.

![Screenshot 2024-01-21 01_02_19](https://github.com/WesselKroos/youtube-ambilight/assets/92368853/af7af0e3-1e44-437d-ac3b-897609801f49)

Testing on other videos, the other settings under "Remove black & colored bars," e.g. "Remove black bars," seem to work.

**Comment by WesselKroos** [comment]
"Fill video to screen." only zooms the video to the available space in the video player when black bars are detected and removed.

I can see where the confusion comes from. Renaming the name of the setting sounds like a good suggestion. What name would you suggest for this feature?

**Comment by zachpoblete** [comment]
Oh, in that case, I would suggest, "Fill video to removed bars."

But hmm, now I've run into a different issue.

I was trying to see if "Fill video to screen" would work for [this video](https://youtu.be/RyVXzzXP7Jg) which has both vertical and horizontal bars.

However, when I'm in theater mode and enable "Remove black bars," it crops the top and bottom of the video.

"Remove black bars" works in default mode, but "Fill video to screen" still isn't doing anything.

| Mode | "Remove black bars" $\color{Red}{\textsf{OFF}}$ ("Fill video to screen" on) | "Remove black bars" $\color{Green}{\textsf{ON}}$ ("Fill video to screen" on) |
| - | - | - |
| Theater | ![image](https://github.com/WesselKroos/youtube-ambilight/assets/92368853/87e31b56-cb21-42ec-8558-1d0212845314) | ![image](https://github.com/WesselKroos/youtube-ambilight/assets/92368853/9a8df187-ccf8-4b58-a2be-be120cef2bf9) |
| Default | ![image](https://github.com/WesselKroos/youtube-ambilight/assets/92368853/ff32cbd0-4474-4f07-966b-5584dd42609b) | ![image](https://github.com/WesselKroos/youtube-ambilight/assets/92368853/937bc246-3dff-433f-af44-588b46c0f718) |

Is "Remove black bars" cropping the top and bottom of the video a new issue? And could you give an example of "Fill video to screen" working?

**Comment by WesselKroos** [comment]
> work for [this video](https://youtu.be/RyVXzzXP7Jg) which has both vertical and horizontal bars.

Interesting... It looks like YouTube is cropping top and bottom black bars on videos with an aspect ratio of 4:3 by themselves now? That's new, and seems to cause the video to be moved down instead.
Btw, the source video has only black bars at the top and the bottom, not on the sides.

Anyway, here is a video on which it still correctly works:
https://www.youtube.com/watch?v=oSxqkER3N6Y
| Original | Removed black bars | Removed black bars + fill to screen |
| -- | -- | -- |
| ![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/af9e53a9-abbb-43fd-bff9-8dbad4a1a15f) | ![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/e9c3515a-371c-4f57-9060-3bd054dc8b01) | ![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/d72ea7bb-03f7-4bb9-b333-d2f4b65249cf) |

**Comment by zachpoblete** [comment]
By the way, what's an example of colored bars being removed?

**Comment by WesselKroos** [comment]
It's most often usefull for videos with white bars https://www.youtube.com/watch?v=O1LPzQsty8U
And there are also old videos with grey bars or you could encounter music videos with colored bars.

**Comment by zachpoblete** [comment]
Ah, I see. I was confused as to why it didn't do anything for [this video](https://youtu.be/zHH2Zan6k9U), but now I understand it's for whites and grays.

Is a delay in removing the bars to be expected whenever the bar size changes?

**Comment by WesselKroos** [comment]
It also works on colored bars. But it does not work on that video because it has large vertical and horizontal bars. Because there is no distinction between the horizontal and vertical bars in the corners. 

Yes, it throttles detection for an x amount of frames to prevent false-positives. Like a concert video shot that pans upwards a rectangled stage where, at night, the sky and the crowd can both be black.

You can turn down the delay though, by turning down the average frames in the advanced bar settings.

**Comment by zachpoblete** [comment]
There seems to be a false positive in [this video](https://youtu.be/RymK-8KFFyg?t=1m11s) when enabling "Remove black sidebars" along with "Also remove colored bars."

After the video pans to the right from 1:11–1:12, the gray backgrounds of Premiere are mistaken for bars even though there are UI elements in the portions that are being cropped.

| Original | Remove sidebars ON |
| - | - |
| ![image](https://github.com/WesselKroos/youtube-ambilight/assets/92368853/d4cce6d8-2f0d-42ea-810b-bdd341ba56d5) |  ![image](https://github.com/WesselKroos/youtube-ambilight/assets/92368853/26689478-084e-4f02-8b82-e20dbf565fd1) |

**Comment by WesselKroos** [comment]
That's because of the small blue line on the left side. There will be many more false-positives with colored bar detection on.

**Comment by WesselKroos** [comment]
Styling these kind of videos seems to be more difficult than expected.

**Comment by WesselKroos** [comment]
>There seems to be a false positive in [this video](https://youtu.be/RymK-8KFFyg?t=1m11s) when enabling "Remove black sidebars" along with "Also remove colored bars."
> > That's because of the small blue line on the left side. There will be many more false-positives with colored bar detection on.

@zachpoblete Since #225 has been released in 2.38.2 it is now possible to tune the aggressiveness of the bar removal feature via the "Detection: Ignored elements" slider.

**Comment by WesselKroos** [comment]
Apparently YouTube zooms in on a video in theater view when it has a `yt:crop` value in it's keywords.
https://youtu.be/RyVXzzXP7Jg has a yt:crop value of 16:9
`<meta name="keywords" content="keywoord1, ..., yt:crop=16:9">`

Removing that keyword from the player's internal list of keywords via the `updateVideoData` function, when the ambient light is enabled, seems to workaround this problem:
`document.querySelector('#movie_player').updateVideoData({ keywords: "keyword1,..." })`
