### ISSUE TITLE
Feature Request: Add support for Nvidia RTX Video HDR

### ISSUE THREAD

**Issue by Verye** [WesselKroos/youtube-ambilight#213]
Very recently Nvidia added a new addition to their latest driver, I believe it's called RTX Video HDR. It uses AI to convert SDR videos, youtube included, into HDR videos. This does require an HDR capable display.

Currently, RTX Video HDR disengages completely when Ambient Light is enabled, as soon as it's disabled, HDR kicks in and there is a drastic improvement to the image, I was actually surprised on the improvement. 

The problem is that on an Ultrawide OLED monitor, this will cause burn in on the sides with black bars, which is why I'm requesting this compatibility as a feature if at all possible.

**Comment by WesselKroos** [comment]
@Verye There is a workaround setting available that enables NVidia RTX. Could you check if that also enables NVidia RTX HDR? Here are the instructions: https://github.com/WesselKroos/youtube-ambilight/issues/202#issuecomment-1817944047

**Comment by Verye** [comment]
Hello @WesselKroos I tried the workaround and it seems to work now, thank you for the help! Replied so others with the same issue can see if the workaround works for them as well.

**Comment by WesselKroos** [comment]
Glad to see that this had the same root cause.

The workaround instructions have now been added to the [Troubleshooter](https://github.com/WesselKroos/youtube-ambilight/blob/master/TROUBLESHOOT.md#3-nvidia-rtx-video-super-resolution-vsr--nvidia-rtx-video-hdr-does-not-work) as well for other users.
