### ISSUE TITLE
(option to) use dark reader to detect "default" Appearance (theme) setting instead of youtube's site default

### ISSUE THREAD

**Issue by kaem-e** [WesselKroos/youtube-ambilight#218]
I use dark reader in conjunction with [auto dark mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) on Youtube for dark mode instead of Youtube's own appearance setting, leaving the Youtube default theme to light, as dark reader allows live reload without refreshing the page. 

Regardless, it seems like Ambilight uses the Youtube's site theme setting to determine whether it should treat the site as being in light or dark mode when you have the `Default` option set in the `Appearance (theme)` setting under general. However this means that when I have my system in dark mode, it will still treat webpages as being light even though dark readers already made the webpage elements dark. 
![scrrenshot of Youtube with light mode styling from Ambilight, while UI elements are dark via dark reader](https://github.com/WesselKroos/youtube-ambilight/assets/46230985/8687785f-7efe-4134-86f0-7d16cd7e7dee)

An option to toggle between detecting dark theme based off of the dark reader setting instead of the site theme when the `Default` option set in the `Appearance (theme)` setting would be ideal. even if its accessed via the "advanced toggle" and is disabled by default would be fine as it would mean people who have a setup such as mine would have a solution, while everyone else would have Ambilight work as normal, as it does now.

Alternatively, it would be nice if Ambilight simply detected the system theme but I don't know how complicated that would be to implement therefore its not the primary solution I thought of

**Comment by WesselKroos** [comment]
Thanks for your suggestion.
Looking at the possible solutions I think using the system theme might be useful for more users. I'm already tracking system theme changes, so I expect that shouldn't take to much work. I'll add a 4th appearance option that will use the system's theme.

**Comment by kaem-e** [comment]
Thank you! that'd be great

**Comment by WesselKroos** [comment]
While reading your question again I come to the conclusion that you'r actually asking for another option, like Current/Ignore. That option should then never modify the theme of the page, so that you can manage the page's theme with another extension.

**Comment by WesselKroos** [comment]
@kaem-e  It took a while, but the new theming behavior is now available on all browsers

**Comment by kaem-e** [comment]
thank you so much !!!!!
