### ISSUE TITLE
Add ability to resize the player controls in theater mode

### ISSUE THREAD

**Issue by ovojake** [WesselKroos/youtube-ambilight#220]
It would be nice to be able to change the width of the player to either fit the video width, rather than the whole width of the screen.

**Comment by WesselKroos** [comment]
I leave the layout of the webpage up to YouTube. This will make sure that the ambient light extension has the least amount of conflicts with other extensions.

Customizing the layout like the player size can be done with other extensions. Or you can customize the layout with your own css rules with extensions like Stylus. 

The only layout customizations I make available are related to transparency of elements to provide more ambient light immersion.
