### ISSUE TITLE
Emote menu doesn't work while replying to a comment

### ISSUE THREAD

**Issue by ovojake** [WesselKroos/youtube-ambilight#222]
### Bug description

While replying to a comment, the emote menu doesn't respond when you click on it. This only happens when replying to comments, and while ambient light is enabled in whatever view mode I'm on (theatre, default etc)

### Steps to reproduce the behavior

1. Have ambient light running
2. Click on emote menu while REPLYING to a comment
3. Disable ambient light
4. Click on emote menu again while replying

### Browser

Microsoft Edge

### Operating system

Windows

### Extension version

2.38.1

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [x] When I logged out of my YouTube account (ex. in incognito mode)
- [x] In incognito mode

### Additional context and/or screenshots

As you can see it works fine when commenting, just not when replying to a comment
[screen-capture (1).webm](https://github.com/WesselKroos/youtube-ambilight/assets/160394602/acac67ed-72a6-4e6c-b64f-d6fd6df7ead2)

**Comment by WesselKroos** [comment]
For now, you can workaround this bug by disabling the "YouTube responsiveness fix" setting.
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/1a90e504-26a4-4ea0-a1a2-139e9e54f467)

**Comment by WesselKroos** [comment]
@ovojake The emoji menu position is now available on all browsers
