### ISSUE TITLE
Support the new YouTube layout with comments on the right side

### ISSUE THREAD

**Issue by WesselKroos** [WesselKroos/youtube-ambilight#223]
YouTube is rolling out a new layout since 22 februari 2024.

Todo:
- [ ] Validate if the new layout has any incompatibilities with the extension

For example this screenshot from a Reddit user:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/269e926e-3c23-4a2a-aa09-5ef8cad02427)

**Comment by WesselKroos** [comment]
It's not the new UI everyone sees, but these are expirement flags that moves the live chat frame to the right side in a fixed position:

[experiment-flags_live-chat_aside.json](https://github.com/WesselKroos/youtube-ambilight/files/14393666/experiment-flags_live-chat_aside.json)

**Comment by WesselKroos** [comment]
The new layout seems to be a combination of new flags. Only the related videos still look the same, the layout has changed to the grid layout.

``` jsonc
  "kevlar_watch_comments_ep_disable_theater": false, // old flag
  "kevlar_watch_comments_panel_button": true,
  "kevlar_watch_grid": true,
  "optimal_reading_width_comments_ep": true,
  "web_watch_compact_comments": true,
  "web_watch_compact_comments_header": true,
  "kevlar_watch_flexy_metadata_height": 90,
  "kevlar_watch_max_player_width": 1560,
  "kevlar_watch_secondary_width": 370,
  "wn_grid_max_item_width": 700,
  "wn_grid_min_item_width": 300,
```

**Comment by kaem-e** [comment]
> It's not the new UI everyone sees, but these are expirement flags that moves the live chat frame to the right side in a fixed position:
> 
> ```json
>   "web_watch_theater_chat": true,
>   "web_watch_theater_fixed_chat": true,
> ```
> 
> [experiment-flags_live-chat_aside.json](https://github.com/WesselKroos/youtube-ambilight/files/14393666/experiment-flags_live-chat_aside.json)
> 
> ![image](https://private-user-images.githubusercontent.com/31220528/307537955-18b67822-3096-42fa-90e6-fe08fa985dca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExODU3MzIsIm5iZiI6MTcxMTE4NTQzMiwicGF0aCI6Ii8zMTIyMDUyOC8zMDc1Mzc5NTUtMThiNjc4MjItMzA5Ni00MmZhLTkwZTYtZmUwOGZhOTg1ZGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDA5MTcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZmNlZjljNTQwNDgwODM4ZDljMThiODBlYmJmZWQyYzQ0MzNkNzc5Y2UwMzMwNzYwMGQ4YTJiZTRlMmE1NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j3LaHYWOqqMzywzQ1vEVnJYptYn1193J6lDHFSUUEwQ)

tangentially related to this, there seems to be an issue with ambilight not being able to properly account for the "show chat reply" button if you collapse the live chat on either a vod of a livestream or an ongoing livestream 

![image](https://github.com/WesselKroos/youtube-ambilight/assets/46230985/70099c0b-dd2c-4a4d-b884-db94233ba1c6)

![image](https://github.com/WesselKroos/youtube-ambilight/assets/46230985/bcb9f315-0695-4ab6-827a-0a9a17f09220)
