### ISSUE TITLE
Ambient Light Stops Rendering in full-screen mode on Ultrawide Screen

### ISSUE THREAD

**Issue by tshih5** [WesselKroos/youtube-ambilight#227]
**Troubleshooter**
First try all the checks and steps in the troubleshooter: https://github.com/WesselKroos/youtube-ambilight/blob/master/TROUBLESHOOT.md
1. Did it solve your performance problems? No
2. What steps made it worse/better: Not much change with different settings

**Describe the performance you are currently experiencing**
3. No issues performance wise other than the fullscreen issue.

**Device information**
4. Name of your CPU: Ryzen 7 7700X
5. Name of your GPU: Nvidia RTX 2070S
6. Name of the browser: Firefox
7. Version of the browser: 124.0
**Screenshots**
9. Add a screenshot of the Task manager with the CPU and GPU usage charts
Full Screen with video playing (Ambient Light is frozen) 
![image](https://github.com/WesselKroos/youtube-ambilight/assets/16581174/ccb27414-7000-4b85-aa17-e6073a0f1071)
Full Screen with video playing (Ambient Light is playing)
![image](https://github.com/WesselKroos/youtube-ambilight/assets/16581174/2275d263-8251-43d9-840c-c213a627d381)

11. Turn on the Ambient light setting Quality > Show framerate and make a screenshot of your framerates
In theater mode with ambient light playing
![image](https://github.com/WesselKroos/youtube-ambilight/assets/16581174/102b9613-f248-4905-9597-4f0c746ca126)
Full Screen mode (ambient light is frozen) (Bar graph also seems to stop moving)
![image](https://github.com/WesselKroos/youtube-ambilight/assets/16581174/41275306-bc44-4143-b598-5aee33b0db18)

**Describe the performance you would be happy with**
12. N/A

**Describe any workaround you've tried so far**
13. Turning on Bar size or changing the video size off of 100% causes rendering to resume, however the video gets cropped. Scrolling down on the video in full screen mode causes ambient light to resume.

**Additional context**
Additonal Images:
Video playing in full screen, ambient light does not play
![image](https://github.com/WesselKroos/youtube-ambilight/assets/16581174/b54e030f-761b-4f38-a38f-b4504f7d6e81)
Scrolling down, in full screen mode, ambient light starts playing
![image](https://github.com/WesselKroos/youtube-ambilight/assets/16581174/b20aa64d-18ee-446b-9346-c317aa5dfd38)

**Comment by WesselKroos** [comment]
> 13. Turning on Bar size or changing the video size off of 100% causes rendering to resume, however the video gets cropped. Scrolling down on the video in full screen mode causes ambient light to resume.

Strange, this hints at the extension thinking that the video is filling the width of you screen (which is obviously not the case). Causing it to pauze the ambilight light to save power. 

1. Is the framerate of the ambilight light in the stats 1 fps when you enable horizontal or vertical bar detection?

2. What is the width of the `<video src="..." />` element in the html? Does it fill the width of your screen?

3. What other extensions / Add-ons are you using?

**Comment by tshih5** [comment]
1. By Vertical/Horizontal bar detection I'm assuming you mean "Remove Black Bars" for the Remove black & colored section. When that setting is checked, it is saying that it is a 30FPS (which is what I have it set to in the `Quality` menu 
![image](https://github.com/WesselKroos/youtube-ambilight/assets/16581174/f54eaba5-4ce9-46bb-9753-26ae45af5be8)
![image](https://github.com/WesselKroos/youtube-ambilight/assets/16581174/ede7cc69-761d-4ed0-8c33-55ce789925f5)
2. the video is 3440x1440, which is the size of my monitor
3. Here are the extensions I am using
![image](https://github.com/WesselKroos/youtube-ambilight/assets/16581174/79539c87-aabe-4abd-b659-bd34daf1d62f)

I think i found the issue, though. I believe UltraWideo was the culprit, turning it off made ambient light play properly again. Not sure why exactly that was the issue, but it is what it is. Thanks for looking into it though. Cheers :D

**Comment by WesselKroos** [comment]
> ...UltraWideo was the culprit, turning it off made ambient light play properly again. Not sure why exactly having that extension on broke the extension...

Aha. In that case UltraWide was stretching the video element to the width of your monitor. Which makes the Ambient light think that the video fills your screen and thus there was no need to draw the ambient light.
