### ISSUE TITLE
Remove the on-hover shadow in theatre mode

### ISSUE THREAD

**Issue by ArcticFox037** [WesselKroos/youtube-ambilight#232]
**Is your feature request related to a problem? Please describe.**
By default, on hover the YT player puts a screen-width black shadow along the bottom while in theatre mode.

**Describe the solution you'd like**
Add an option to disable this shadow

**Comment by WesselKroos** [comment]
Do you have a screenshot of this shadow? I'm wondering if we are seeing the same shadow.

**Comment by ArcticFox037** [comment]
![image](https://github.com/WesselKroos/youtube-ambilight/assets/38768897/93e41af7-7b63-44f8-942e-387ef3df9cc1)
Just above the title

**Comment by WesselKroos** [comment]
On bright videos it becomes very hard to scrub the timeline and use the controls when you remove the shadow. So, I won't be making this an option, to prevent confusion.

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/63e6df05-861d-4bc4-983c-d07765106d70)

However, you can hide the shadow yourself via this css rule in the Stylus extension:
```css
.ytp-gradient-bottom {
  display: none !important;
}
```

**Comment by ArcticFox037** [comment]
Ah, I didn't consider that. But thank you for the CSS at least!
