### ISSUE TITLE
Disable ambilight in full screen option

### ISSUE THREAD

**Issue by sdpsbpsdp** [WesselKroos/youtube-ambilight#233]
currently using latest macos, mainly on brave browser. in full screen mode we prefer black top and bottom bars. It would be nice if there was an auto disable ambilight while in full screen option, thanks

**Comment by WesselKroos** [comment]
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/2c3f3c7b-8020-4416-80c5-09f5269d094e)
