### ISSUE TITLE
Small black line visible on Firefox when using Ambilight with Fullscreen Youtube on 21:9 monitor

### ISSUE THREAD

**Issue by Violins77** [WesselKroos/youtube-ambilight#238]
### Bug description

When Youtube is set to full screen on an Ultrawide (21:9) monitor using Firefox 126.0 (64-bit) and Ambilight, a small but noticeable blackline is visible on the left side of the video between the video itself and ambilight. Disabling hardware acceleration in Firefox solves the issue, but obviously performance is not acceptable. This issue is reported by me because I use ambililight to watch 16:9 video on an ultrawide OLED display and this black bar can lead to burn in of the OLED if used for an extensive period of time.

### Steps to reproduce the behavior

Assuming you have Amblight installed and activated to work in Youtube fullscreen on an 21:9 (possibly wider as well, but couldn't test) monitor

1-Go to youtube.com
2-Play a video in fullscreen using ambilight
3-Look on the left side to see the black line

### Browser

Firefox

### Operating system

Windows

### Extension version

2.38.5

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

![image](https://github.com/WesselKroos/youtube-ambilight/assets/34794597/4804ec05-4fb2-4f86-9891-347830fe763e)

**Comment by brutlern** [comment]
I have also noticed this, but it doesn't always happen. For me, it only happens on specific videos, like https://www.youtube.com/watch?v=ZSREFnnUnhI 
![image](https://github.com/WesselKroos/youtube-ambilight/assets/39137520/86914a4c-20e3-45a3-a935-947180456b7b)
I think it just might be how the original video is encoded/uploaded. All the videos where I can reproduce the issue are 1080p50. Any other resolution or frame rate and I don't have any black bars.
I found the video that the OP posted (please provide link next time) and I don't have the black bars
![image](https://github.com/WesselKroos/youtube-ambilight/assets/39137520/a3e67797-d509-4a69-83d0-efea6bc5642b)

**Comment by WesselKroos** [comment]
I think this is caused by the MPO feature in Windows. This is likely a bug in the graphics card driver.

I had the same issue on an Intel laptop in Chromium:
https://issues.chromium.org/issues/40228515#c_ts1667004785

This has probably the same cause but for Firefox. You might want to try to disable the hardware overlays for videos flag in Firefox. This disables the MPO feature.

**Comment by Violins77** [comment]
I can confirm that the following setting does not fix it for me:

![image](https://github.com/WesselKroos/youtube-ambilight/assets/34794597/8b945831-3eb2-4702-ac8a-f278a2beafe6)

**Comment by WesselKroos** [comment]
I can confirm it's an overlay issue. I can reproduce this on my Intel laptop when I set `gfx.webrender.dcomp-video-yuv-overlay-win` to `true` and restart Firefox. So you might want to set the `gfx.webrender.dcomp-video-sw-overlay-win` and/or `gfx.webrender.dcomp-video-hw-overlay-win` settings to `false` and restart Firefox to see if it fixes it.

**Comment by WesselKroos** [comment]
For chromium i'm already applying a workaround to disable the direct video overlay (MPO).
Firefox seems to need another workaround. I was able to fix the black lines with these css rules:

``` css
html[data-ambientlight-enabled="true"] .html5-main-video {
  transform: translate3d(0,0,0);
  backface-visibility: hidden;
}
```

@Violins77 @brutlern Could you check if this workaround also works for you? I can apply this workaround on Firefox in the next update if it works for you as well.

**Comment by Violins77** [comment]
I confirm that the fix you provided fixes the issue for me. It took ma little while as I'm not too familiar with front end development, but it really does fix it.

Thank you

**Comment by WesselKroos** [comment]
The "Video artifacts workaround" (advanced) setting is now also available on Firefox and enabled by default to prevent these artifacts from happening:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/0e25c691-34bf-4533-8f39-23c880d30500)
