### ISSUE TITLE
Disabled buttons aren't colored correctly

### ISSUE THREAD

**Issue by avi12** [WesselKroos/youtube-ambilight#243]
### Bug description

Disabled buttons aren't colored correctly

### Steps to reproduce the behavior

1. https://www.youtube.com/watch?v=cev4185JuF8
2. ![image](https://github.com/WesselKroos/youtube-ambilight/assets/6422804/d26818d5-5c54-49b5-8229-007a88283013)

### Browser

Microsoft Edge

### Operating system

Windows

### Extension version

2.38.7

### The bug still happens in these conditions

- [ ] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [ ] When I logged out of my YouTube account (ex. in incognito mode)
- [ ] In incognito mode

### Additional context and/or screenshots

In this case, it's a video labeled for kids

**Comment by avi12** [comment]
When I clicked the Share button it didn't let me share the video because it is "kids friendly"

**Comment by WesselKroos** [comment]
My share button is not disabled on a kids friendly video

**Comment by avi12** [comment]
https://github.com/WesselKroos/youtube-ambilight/assets/6422804/97ebfca6-ea0e-49fd-b349-cf94a2d4a0fb

**Comment by WesselKroos** [comment]
Got it, I had to login.

YouTube light:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/cd5d6a49-5c80-48e8-bc9a-0da8323e2635)

YouTube light + Ambient light:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/5ec50168-d3dc-4e1c-a02c-2f324fb52933)

YouTube light + Ambient dark:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/70cf5ada-8cb5-4fc3-85d9-825bf7b31752)

YouTube dark:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/21f0218c-7b0f-4b66-b251-f5debba0c9a0)

YouTube dark + Ambient light:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/5caf8c03-da7b-414f-bcf0-dd18fdf7d753)

YouTube dark + Ambient dark:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/cb72eca9-32c2-4603-a528-bab5fb9c64f4)

Todo:
- [ ] Override the selector: `.yt-spec-button-shape-next--disabled.yt-spec-button-shape-next--tonal`
- [ ] Change the gray text color on a disabled button to semi transparent black/white
- [ ] Change the background color of a disabled button to semi transparent black/white

**Comment by WesselKroos** [comment]
Changed disabled buttons styling to:

Ambient dark:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/d8944d0a-f492-4c1b-b4fa-e22a88a1875f)

Ambient light:
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/995ac77f-8454-438b-acb2-bd4bd9493022)
