### ISSUE TITLE
An activated Like button loses its fill

### ISSUE THREAD

**Issue by avi12** [WesselKroos/youtube-ambilight#244]
### Bug description

An activated Like button loses its fill

### Steps to reproduce the behavior

1. Go to any video
2. Open a video that you have already liked in a new tab
3. Wait for the new tab to finish loading

### Browser

Microsoft Edge

### Operating system

Windows

### Extension version

2.38.7

### The bug still happens in these conditions

- [ ] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [ ] When I logged out of my YouTube account (ex. in incognito mode)
- [ ] In incognito mode

### Additional context and/or screenshots

https://github.com/WesselKroos/youtube-ambilight/assets/6422804/67b6869f-ef99-4bf3-8f7e-8ff821ae3428

**Comment by WesselKroos** [comment]
This is a bug for YouTube. The whole like icon is removed from the html after clicking on the like button.

![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/6a456666-a5bf-4783-9b66-f7a9874a4432)
![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/d782cad5-8149-4dad-b686-8b3b3adcf156)

**Comment by avi12** [comment]
Man, I'm such a bug hunter 😂

**Comment by WesselKroos** [comment]
I don't mind. I'm quite the bug hunter myself.
And I would rather have a few false positives than no bug reports at all 😉
