### ISSUE TITLE
Like button is not clickable over the icon anymore

### ISSUE THREAD

**Issue by NotOnii** [WesselKroos/youtube-ambilight#245]
### Bug description

The Ambient Light partially blocks the like button

### Steps to reproduce the behavior

1. Go to any YouTube Video
2. Try clicking the like button with Ambient Light turned on
3. Try clicking the like button with Ambient Light turned off

Toggling the ambient light (with G) seems to fix the issue until I turn it back on. The like button is still clickable anywhere else on the button where the icon isn't being blocked by Ambient Light.

### Browser

Chrome

### Operating system

Windows

### Extension version

2.38.7

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

**Comment by WesselKroos** [comment]
I wouldn't be surprised if it has something to with the fix YouTube had to fix their previous bug that completely removed the like icon #244

**Comment by NotOnii** [comment]
This has been happening since the same day I actually got the disappearing like button bug, so I don't think it's specifically from them pushing a hotfix for it.

**Comment by WesselKroos** [comment]
Aha, so they broke it earlier. Thanks for the tip. I'll take a look in the evening
