### ISSUE TITLE
Black bar detection performance issues

### ISSUE THREAD

**Issue by Askejm** [WesselKroos/youtube-ambilight#247]
**Troubleshooter**
First try all the checks and steps in the troubleshooter: https://github.com/WesselKroos/youtube-ambilight/blob/master/TROUBLESHOOT.md
1. Dit it solve your performance problems? yes/no
2. What steps made it worse/better:

**Describe the performance you are currently experiencing**
3. Enabling black bar detection causes significant stuttering on the entire video, not just the bars

**Device information**
4. Name of your CPU: 5800x3d
5. Name of your GPU: 3090
6. Name of the browser: Firefox 
7. Version of the browser: 126.0.1

On: 
![image](https://github.com/WesselKroos/youtube-ambilight/assets/55248977/3da6a6d5-75da-41d7-a732-96ca03b9eeeb)
Off: 
![image](https://github.com/WesselKroos/youtube-ambilight/assets/55248977/6e34273f-cce1-4ff9-be21-b7afb8c452ba)

**Comment by WesselKroos** [comment]
Did this happen after the update to version 2.38.8?

**Comment by WesselKroos** [comment]
@Askejm I have fixed the bug in version 2.38.9. You should be able to update to that version manually.

**Comment by Askejm** [comment]
Oh sorry, I don't know why Firefox didn't update!

**Comment by WesselKroos** [comment]
Nothing to be sorry about. 

There was no update. I updated the extension to fix your issue. So, thanks for the report!
