### ISSUE TITLE
"Ambient light loading is paused"

### ISSUE THREAD

**Issue by AlexJohn73** [WesselKroos/youtube-ambilight#255]
### Bug description

Ambient light for YouTube doesn't bother fully loading and complains it is waiting for the webpage and video to fully load, which they are. This means I can't access the settings to try and fix it

### Steps to reproduce the behavior

1. Sign into YouTube
2. Open any video
3. Ambient light gives the following message when I hover over it:

> Ambient light loading is paused.
> Waiting for the video and page to be loaded first

### Browser

Chrome

### Operating system

Windows

### Extension version

2.38.9

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [ ] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

### Additional context and/or screenshots

I am using Vivaldi 6.8.3381.50. The bug only happens when signed in. It persists in incognito mode. I would try to export my very finely tuned settings to attempt a re-install but whilst this is successful, I have no idea where they are exported to!

The webpage is definitely fully loaded and doesn't appear any different to what I'm familiar with. Clicking the AL settings icon doesn't do anything or allow me to change any settings. Happy to provide additional info/testing if needed.

![image](https://github.com/user-attachments/assets/9831b454-9b05-4a41-bab4-c5cb564219d8)

**Comment by WesselKroos** [comment]
No problem. I don't think your exported settings would help me in this case.

1. Did you try it in incognito mode with all other extensions disabled?

2. Since it only happens when you have signed in, it could also be caused by a new test from YouTube. In that case I need the ytconfig to reproduce the bug. I'll provide the steps on how to copy the ytconfig in a few minutes.

**Comment by AlexJohn73** [comment]
Hi @WesselKroos , thanks for the prompt response! I've checked my Downloads folder where Vivaldi saves by default and there doesn't appear to be anything in there...

Anyhow, here's the requested information:

1. {H5_enable_full_pacf_logging: true, H5_use_async_logging: true, PremiumClientSharedConfig__enable_att_context_processor: true, PremiumClientSharedConfig__enable_att_for_get_premium_on_web_client: true, ab_det_apb_b: true, …}
2. Yes, quite a few actually. A few relate to Ambient Light; let me know if you'd like me to expand any for further info.
![image](https://github.com/user-attachments/assets/b6cf9618-8261-4d56-9138-86118bb67940)

**Comment by WesselKroos** [comment]
Aha, it seems that YouTube suddenly uses the [TrustedHTML api](https://developer.mozilla.org/en-US/docs/Web/API/TrustedHTML). That's a big change, I suspect you will see other extensions failing as well (or behaving strangely) in the coming days.

That also explains the sudden spike in error reports over the past 5 hours, so at least you're not the only one, just the first one to report it:
![image](https://github.com/user-attachments/assets/fbae452c-1b8e-4294-b23d-7dd5dce91ef8)

I'll check if I can workaround this error quickly and submit a new version tomorrow. And we have to hope that Google reviews the new version quickly before the weekend. Else you might have to wait till monday...

**Comment by AlexJohn73** [comment]
Ah awesome, thanks so much for looking into this so quickly! Ambilight is a bit of a necessity for me as an ultrawide OLED user, but Monday seems generous in my eyes lol. More than happy to wait until then, at least you're now aware of a rather important change! (:

**Comment by WesselKroos** [comment]
@AlexJohn73 Could you test if this version fixes the error when you are logged in?

[youtube-ambilight-v2.38.9.1 mv2 - alpha.zip](https://github.com/user-attachments/files/16460398/youtube-ambilight-v2.38.9.1.mv2.-.alpha.zip)

To add the extension to the browser:
1. Download and unzip the file to a directory
2. Go to the url chrome://extensions
3. Disable the existing Ambient light for YouTube™ extension with version 2.38.9
4. Turn on the Developer mode toggle
5. Click "Load unpacked" and select the unpacked directory
6. A second Ambient light for YouTube™ extension should have been added to the list of extensions.
You can recognize the new 2.38.9.1 mv2 alpha version by the orange circle on top of the icon:
![image](https://github.com/user-attachments/assets/43b1ef64-6022-4aff-b52b-62afbe8ea82e)
(And a warning about Manifest version 2 being deprecated)
7. Open a new YouTube tab or refresh an existing one

**Comment by WesselKroos** [comment]
I've managed to mimic the TrustedHTML requirement. 
The extension functions, but there is a second TrustedHTML error that causes the black bar detection to run on the main thread instead of in a separate worker thread.
I'll have to investigate a fix for that as well...

**Comment by AlexJohn73** [comment]
> It took 4 hours but I believe I have a fix. @AlexJohn73 Could you test if this alpha version fixes the error when you are logged in?
> 
> **(Anyone else with the error is also invited to test this alpha version)**
> 
> To add the extension to the browser:
> 
> 1. Download and unzip this file to a directory: [youtube-ambilight-v2.38.9.1 mv2 - alpha.zip](https://github.com/user-attachments/files/16460398/youtube-ambilight-v2.38.9.1.mv2.-.alpha.zip)
> 2. Go to the url chrome://extensions
> 3. Disable the existing Ambient light for YouTube™ extension with version 2.38.9
> 4. Turn on the Developer mode toggle
> 5. Click "Load unpacked" and select the unpacked directory
> 6. A second Ambient light for YouTube™ extension should have been added to the list of extensions.
>    You can recognize the new 2.38.9.1 mv2 alpha version by the orange circle on top of the icon:
>    ![image](https://private-user-images.githubusercontent.com/31220528/354333386-43b1ef64-6022-4aff-b52b-62afbe8ea82e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NDQyODUsIm5iZiI6MTcyMjU0Mzk4NSwicGF0aCI6Ii8zMTIyMDUyOC8zNTQzMzMzODYtNDNiMWVmNjQtNjAyMi00YWZmLWI1MmItNjJhZmJlOGVhODJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDIwMjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMjc0NDg1NWZlYjU4Nzc1NDViNGJjNjJiNzkyMGVmMDk2MTE3N2ZhNGFkNzExMWYwMGI0MWU1YWRjZjg3NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VxBAPyQWwRAfjqAKWJAqvKrKpge3nSnHk9LBFFuQ9l4)
>    (And it has a warning about Manifest version 2 being deprecated)
> 7. Open a new YouTube tab or refresh an existing one

I can confirm this alpha has fixed the issue!



> I've managed to mimic the TrustedHTML requirement. The alpha version functions, but there is a second TrustedHTML error that causes the black bar detection to run on the main thread instead of in a separate worker thread. I'll have to find a fix for that as well...
> 
> ![image](https://private-user-images.githubusercontent.com/31220528/354346380-6e69417e-5888-4ece-9b32-5c38f8827482.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NDQyODUsIm5iZiI6MTcyMjU0Mzk4NSwicGF0aCI6Ii8zMTIyMDUyOC8zNTQzNDYzODAtNmU2OTQxN2UtNTg4OC00ZWNlLTliMzItNWMzOGY4ODI3NDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDIwMjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MzE5ZTdkODE1ZWI1ZTlmM2YzMDAyMTIxNzI3YWYyZGM1MDkwMDZiNTAyOGQ4NzcxN2I1YTJiOTBjY2RiZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6eysx4tEhznXZNmo8zRcSSflBTuq71XrO1VgE0Su5Do)
> 
> @AlexJohn73 Let me know if you see the same error as well or any other errors

I've had a good look at the console and I can't see any errors relating to Ambient light or the ones you've screenshotted.

**Comment by WesselKroos** [comment]
> I've had a good look at the console and I can't see any errors relating to Ambient light or the ones you've screenshotted.

Thanks for the verification! In that case my mimicked way went a little to far.
I'm going to publish the new version. Let's find out if Google can review the extension in time tomorrow 😄

**Comment by WesselKroos** [comment]
@AlexJohn73 A last request. Could you check which `Content-Security-Policy` header value YouTube returns as response for the /watch page request?

1. Open the **DevTools**
2. Open the **Network** tab
3. Refresh the webpage
4. Optional: Click on the **Doc** filter
5. Click on the `watch?v=...` request (In case there are 2 requests check them both)
6. Click on the **Headers** tab
7. Search for a `Content-Security-Policy` header in the **Response headers** section (They are ordered alphabetically)
![image](https://github.com/user-attachments/assets/5ebe268b-75fb-41d5-9f03-5ec2231670a6)

I've mimicked it by setting the header value to `require-trusted-types-for 'script'`, but am wondering if YouTube uses another value, since you did not see these additional errors/warnings

**Comment by WesselKroos** [comment]
Good news!
I've submitted a new version (2.38.10) containing the first fix to all stores last evening. And Chrome, Firefox and Opera have already updated the extension to version this morning.

So it should be functional again.
And I'll probably release a new version with the re-optimized features that use a webworker (black bar detection and energy saver) somewhere next week. It depends on how quickly I can remove the bugginess.

**Comment by AlexJohn73** [comment]
> Good news! I've submitted a new version (2.38.10) containing the first fix to all stores last evening. And Chrome, Firefox and Opera have already updated the extension to version this morning.
> 
> So it should be functional again. And I'll probably release a new version with the re-optimized features that use a webworker (black bar detection and energy saver) somewhere next week. It depends on how quickly I can remove the bugginess.

Thanks so much for the quick turnaround! It is working in the official release now. :)

With regards to your final request, I can confirm my Content-Security-Policy is the same as what's in your screenshot.

**Comment by WesselKroos** [comment]
@AlexJohn73 [Vivaldi seems to have a bug with Blob downloads since march](https://forum.vivaldi.net/topic/95819/download-dialog-not-shown-on-some-websites/54)

In the next version (2.38.11) you can also manually save the exported json file via a generated link in case the browser blocks the download:

![image](https://github.com/user-attachments/assets/bd664010-295b-4542-8fbd-f5064c130096)
