### ISSUE TITLE
Disable Extension

### ISSUE THREAD

**Issue by ItsEpicBeast** [WesselKroos/youtube-ambilight#264]
### Bug description

When uninstall the extension, it is still active somehow

### Steps to reproduce the behavior

The extension keeps on working even if its uninstalled. Is there a way to disable the affects even if I decide to keep it?

### Browser

Chrome

### Operating system

Windows

### Extension version

2.38.10

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [ ] When I logged out of my YouTube account (ex. in incognito mode)
- [ ] In incognito mode

**Comment by WesselKroos** [comment]
You need to refresh the webpage after you have installed or uninstalled an extension. That's how browsers add/remove extensions from/to webpages.

If it is still active after those steps, then you have discovered a Chromium (Chrome) browser bug, which you can report to the Chromium developers via this form: https://issues.chromium.org/issues/wizard

**Comment by ItsEpicBeast** [comment]
I saw the video of the extension and there is no enable option on the extension like on the video

**Comment by WesselKroos** [comment]
I suspect you are seeing the YouTube's own ambient mode, which you can disable in YouTube's settings:

![image](https://github.com/user-attachments/assets/d847073b-60d1-4d93-a0b3-0528c9385994)

If not, can you make a screenshot of the ambient effect you are still seeing?

**Comment by WesselKroos** [comment]
@ItsEpicBeast I saw that you wrote a 3 star review but removed it after a few hours. Did you find out that it was YouTube's own ambient mode or was there something else you found out that would be helpful for me to know?

**Comment by ItsEpicBeast** [comment]
@WesselKroos Another extension that I was using was interfering with your extension, so I also had to delete it in order to get youtube back to normal.

**Comment by WesselKroos** [comment]
Aha, thanks for the explanation. Which other extension was interfering?

**Comment by ItsEpicBeast** [comment]
It's called Turn Off the Lights
