### ISSUE TITLE
Flickering and stuck frames with WebGL on Firefox 131

### ISSUE THREAD

**Issue by Askejm** [WesselKroos/youtube-ambilight#265]
### Bug description

Flickering appears and frames are stuck. When I disable WebGL renderer, this is resolved but then I get bad performance

### Steps to reproduce the behavior

1. Enable WebGL renderer
2. Go to a video [like this one](https://youtu.be/gYFZ4HYTsZI?si=USM5ScXZF5ZavmmQ&t=193)
3. Observe flickering 

### Browser

Firefox

### Operating system

Windows

### Extension version

2.38.10

### The bug still happens in these conditions

- [ ] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [ ] When I logged out of my YouTube account (ex. in incognito mode)
- [ ] In incognito mode

### Additional context and/or screenshots

https://streamable.com/n2dmsb
5800x3d 
3090

**Comment by WesselKroos** [comment]
I'm unable to reproduce this on Firefox. 

1. Are there any relevant errors logged to the javascript console (F12 > Console tab)?
2. What's your version of Firefox?
3. Do you have any flags manually enabled/disabled in the Firefox config (url: `about:config`)
4. Could you export your extension settings?

**Comment by Askejm** [comment]
1. Im mostly getting errors like this 
 `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.google.com/log?format=json&hasfast=true&authuser=0. (Reason: CORS request did not succeed). Status code: (null).`
2. 131.0, now that I look it seems that it updated today 
3. Only stuff for the fade transition, nothing else 
4. [ambient-light-for-youtube-settings.json](https://github.com/user-attachments/files/17230152/ambient-light-for-youtube-settings.json)
I'm still on nvidia driver 560.81 (august 2024)

**Comment by WesselKroos** [comment]
Bug reported to Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1922291

**Comment by WesselKroos** [comment]
Luckily we're not the only ones. Firefox's bugged feature is also used by YouTube's VR videos:
https://bugzilla.mozilla.org/show_bug.cgi?id=1922278

**Comment by Askejm** [comment]
> Or you can always prefer the AV1 encoded video format in the YouTube settings, but not all YouTube videos are encoded in AV1, so some will still fail:

Still appears when streaming AV1 
![image](https://github.com/user-attachments/assets/75e12d7b-980b-4179-8719-761091551c53)
(As you can see, the ambient lights is stuck on an old frame)

**Comment by WesselKroos** [comment]
Mozilla will release a new Firefox version with the fix [on October 15th.](https://bugzilla.mozilla.org/show_bug.cgi?id=1922278#c14)

**Comment by Askejm** [comment]
Updated and confirmed working on 131.0.3
