### ISSUE TITLE
Simple rounded corners for cinema view

### ISSUE THREAD

**Issue by Blu3NTV** [WesselKroos/youtube-ambilight#271]
The default youtube view for a video has rounded corners, but then when it's put into cinema view it doesn't. it would be nice to have a new option that let's us add or remove ronded corners on either default or cinema view, and also let us change how rounded it is.
it would also be nice to fix the shadow overlay when hovering over the video to be just on the video rather than over the ambient light effect as well, this can be seen in the second photo and a crude mocup I did in photoshop to illustrate my point as the 3rd picture

![Screenshot 2024-11-13 063948](https://github.com/user-attachments/assets/5493e03a-ec95-417e-8c21-706155978311)
![Screenshot 2024-11-13 064133](https://github.com/user-attachments/assets/077d059a-2500-4874-9d4b-21e6b9a16bbb)
![Screenshot 2024-11-13 064424 crop](https://github.com/user-attachments/assets/4e82918d-53c6-4fd8-820c-2ef519a54c96)

**Comment by WesselKroos** [comment]
Thanks for your feature requests, but I've currently no plans to add these features. Here are the answers I've given on previous requests with workarounds to add these features yourself:

## Request 1
> The default youtube view for a video has rounded corners, but then when it's put into cinema view it doesn't. it would be nice to have a new option that let's us add or remove ronded corners on either default or cinema view, and also let us change how rounded it is.

Answered in https://github.com/WesselKroos/youtube-ambilight/issues/219#issuecomment-1951438188
> Upon further inspection I won't implement this feature. It goes against the philosophy of keeping the YouTube layout as close as possible to the original. And it will also be more complicated than just a single setting, because you could want rounded borders in small, theater or fullscreen mode, a specific roundness size. And I can image that some users also want the rounded borders in fullscreen when the video does not completely fill the screen because of removed borders or the video being a different aspect ratio than their screen. This introduces a lot of complexity.
> 
> As alternative you could install an extension like [Stylus](https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) with which you can customize the css on the webpage and add these css rules to get the rounded borders in theater mode:
> 
> ```css
> ytd-watch-flexy[rounded-player-large][theater] #ytd-player.ytd-watch-flexy .html5-video-container,
> ytd-watch-flexy[rounded-player-large][theater] #ytd-player.ytd-watch-flexy .html5-main-video {
>     border-radius: 12px !important;
> }
> ```

## Request 2

> it would also be nice to fix the shadow overlay when hovering over the video to be just on the video rather than over the ambient light effect as well, this can be seen in the second photo and a crude mocup I did in photoshop to illustrate my point as the 3rd picture

Answered in: https://github.com/WesselKroos/youtube-ambilight/issues/232#issuecomment-2049703609 
> On bright videos it becomes very hard to scrub the timeline and use the controls when you remove the shadow. So, I won't be making this an option, to prevent confusion.
> 
> ![image](https://github.com/WesselKroos/youtube-ambilight/assets/31220528/63e6df05-861d-4bc4-983c-d07765106d70)
> 
> However, you can hide the shadow yourself via this css rule in the Stylus extension:
> 
> ```css
> .ytp-gradient-bottom {
>   display: none !important;
> }
> ```
