### ISSUE TITLE
Resolution settings opening on pause,play and forward/back. conflict with Enhancer for YouTube

### ISSUE THREAD

**Issue by DJGoo** [WesselKroos/youtube-ambilight#63]
**Describe the bug**
whenever an action happens to a video, be it via keyboard, Bluetooth headset controls, Logitech mouse macros or presumably anything, YouTubes resolution settings opens or closes after most general controls. this appears to be a conflict with [Enhancer for YouTube](https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle) as it has a setting to force set resolutions.

**Steps to reproduce the behavior:**
1. Install [Enhancer for YouTube](https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle)
2. Enable "Automatically play videos at my preferred quality" (it won't matter to what resolution probably)
3. Load a video and play
4. Spam rewind or click to play/pause
5. resolution settings open after the video command/s end (or so it seems)

**Expected behavior:**
I would just like to be able to spam the left key to rewind when someone talks over a video without the settings opening repeatedly.

**Desktop:**
 - OS: Windows 10 Pro x64
 - Version/Build: 2004/10.0.19041
 - Browser: Chrome Canary
 - Version 89.0.4340.0 (Official Build) canary (64-bit)

**Additional context**
I tested without Enhancer for YouTube enabled and the error did not occur. There are also other conflicts with this extension I think but non that noticeable other than this.
A likely related error is once Ambilight was installed it also prevents Enhancer for Youtube changing the resolution from auto when a video starts.
I have not tested this error in Firefox.

Ps: Ambilight is very impressive for what it does in real-time, and how easy it is to use. 
I appreciate that its probably a lot of work to develop, and in my opinion, it works great, runs pretty well and if it doesn't, it is as simple and capable to configure as it should be.
I'm looking forward to any potential updates.

**Comment by WesselKroos** [comment]
It looks like the extension is setting the quality of the video via de quality menu that is used by the user. My guess is that it has a conflict with the ambilight menu or is waiting for the quality menu to appear within a maximum timeframe (for example 500 milliseconds). But your computer is busy rendering the ambilight so the computer is unable to show the menu within that timeframe.
It would be better for the **Enhancer for YouTube** extension to set the playback quality directly via code. That way the extension cannot conflict with menu's of other extensions and is not dependent on the performance of the computer.

A code example which gets and sets the playback quality:
``` javascript
var player = document.querySelector('#movie_player');
var currentLevel = player.getPlaybackQuality();
// Example: currentLevel = 'medium'
var availableLevels = player.getAvailableQualityLevels();
// Example: availableLevels = ["hd1080", "hd720", "large", "medium", "small", "tiny", "auto"]
player.setPlaybackQualityRange('hd1080', 'hd1080');
```

@DJGoo Have you reported the bug to the developer aswell via http://improvedtube.com/contact ?

**Comment by WesselKroos** [comment]
@DJGoo Were you able to resolve the issue with the **Enhancer for YouTube** extension team?

**Comment by DJGoo** [comment]
Sorry I haven’t had a chance to follow it up yet, it’s a rough time of year.
I do intent to contact the devs of Enhancer for Youtube but I just haven’t gotten to it yet.

I did discover that by turning on sync video with ambilight, turning off smooth motion, and in: Nvidia Control Panel/Manage 3D Settings/Chrome, changing  ‘Virtual Reality pre-rendered frames’ from the default 1 to ‘use the 3D application setting’ seemed to allow chrome to run at and above my refresh rate (90) much easier which seems to have reduced how often the bug occurs. That does seem to indicate as you said that it may be related to a delay.

**Comment by WesselKroos** [comment]
No problem. 
If it's related to performance you might want to try out the "Synchronization" option "Best" when release 2.36.0 (#65) is out for Chrome (Or try out Opera that has the update already). The release contains a bunch of other performance improvements as well in the "Balanced" synchronization mode and the "Remove black bars" feature.

The combined performance improvements should allow you to even play 8k60fps videos in 90hz if you've got a powerful graphics card. (I was able to jump from 15hz to 144hz).

**Comment by WesselKroos** [comment]
The pending release 2.36.4 (#65) contains performance improvements in the "page content shadow". Thath might also resolve the issue.

**Comment by WesselKroos** [comment]
I'm closing this issue since all browsers now contain the above mentioned performance improvements. Feel free to open a new bug if there is still a problem.
