### ISSUE TITLE
Hide grey bar

### ISSUE THREAD

**Issue by Oxize** [WesselKroos/youtube-ambilight#71]
Is it possible to remove this bar from Theater mode (not full screen). I have hide scrollbar enabled, but it does nothing in theater mode (theater mode and then F11).

![](https://i.imgur.com/D6uLHQD.png)

**Comment by WesselKroos** [comment]
Thanks for the report.
It seems like YouTube changed their scrollbar. I'll take a look.

**Comment by WesselKroos** [comment]
@Oxize The issue has been fixed. You can follow the release progress here: #72
