### ISSUE TITLE
Parts of the ambient light or video has sometimes flickering black triangles or triangles that contain the previous video frame

### ISSUE THREAD

**Issue by red9350** [WesselKroos/youtube-ambilight#97]
Ambilight randomly flickers black when watching a video. Setting chrome's #use-angle flag to OpenGL seems to fix it but drastically lowers the ambilight fps.
It could also be linked to Windows HDR, as it's way more prevalent with HDR turned on 

Reproduced on both Windows 10 and 11.
Chrome 95.0.4638.54

[I uploaded a video of the issue here, you can see the flickering at 0:17 and 0:27](https://youtu.be/XjCEBAB2HDg)
(the colors in the video are off because i recorded the display with HDR turned on)

**Comment by Nirgranth** [comment]
Same in Brave 
HW:
2060
3800x

**Comment by WesselKroos** [comment]
Todo:
- [ ] Check if this bug still happens after the workaround for bug #150 is released

**Comment by WesselKroos** [comment]
@red9350 @Nirgranth This is now fixed in version 2.37.2 (Already released to Opera but in review for Edge and Chrome)
